Add post mortem for Sept. 3, 2020
openSUSE/obs-landing pull request #268
Opened 2020-09-07 16:31 UTC by dmarcoux

2020-09-07 16:32 UTC, hennevogel commented
Deploy preview for *openbuildservice* ready!

Built with commit 7a8a34c000c94c4c24d7a2935c60cdd6c457745b

https://deploy-preview-268--openbuildservice.netlify.app

2020-09-07 16:52 UTC, eduardoj requested changes
In my honest opinion, there were some things missing, that after being added would help to clarify everything what happened.

2020-09-07 16:52 UTC, eduardoj commented on _posts/deployments/2020-09-03-post-mortem.md
> +Nobody could search.
I will also add that every part of the application that required a callback to update the Sphinx indices, returned a 500 error. That gave the false impresion to the users that something was really wrong with OBS, when only the update to the Sphinx indices was affected.

And until the reindex procces was finished, searching for some terms didn't return all the results expected.

2020-09-07 16:52 UTC, eduardoj commented on _posts/deployments/2020-09-03-post-mortem.md
> +
These left out files we had to remove, were created by starting up the daemon with a direct call to the Sphinx daemon, as root. We should have started the daemon with the `systemctl start obs-sphinx.service` command.

2020-09-07 18:31 UTC, dmarcoux commented on _posts/deployments/2020-09-03-post-mortem.md
> +Nobody could search.
True, I will add this.

2020-09-07 18:32 UTC, dmarcoux commented on _posts/deployments/2020-09-03-post-mortem.md
> +
In the heat of the moment, I didn't remember exactly why it was the case. I will explain this better.

2020-09-07 18:48 UTC, dmarcoux commented
@eduardoj Please have another look.

2020-09-07 18:57 UTC, eduardoj commented
> @eduardoj Please have another look.

Nice, thanks!

2020-09-07 18:57 UTC, eduardoj approved these changes

2020-09-07 19:04 UTC, dmarcoux commented
I pushed again to fix a typo I found.

2020-09-08 10:35 UTC, hennevogel requested changes

2020-09-08 10:35 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +caused errors (500) while the search was down. Project and package pages were
We know how many people where affected by this?

2020-09-08 10:35 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +while doing so.
So the root cause is `sphinx` crashing during the deployment, leaving behind unclean state.

2020-09-08 10:35 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +stopped when the searchd process crashed and couldn't be restarted.
This is not the trigger. What made sphinx crash?

2020-09-08 10:37 UTC, dmarcoux commented on _posts/deployments/2020-09-03-post-mortem.md
> +attempted to fix an issue in our this process is tracked and monitored. The
Oh right, `in our this` should be `in how this process`

2020-09-08 10:39 UTC, dmarcoux commented on _posts/deployments/2020-09-03-post-mortem.md
> +caused errors (500) while the search was down. Project and package pages were
I don't remember the exact number, I think we had about 200 errors in Errbit.

2020-09-08 12:38 UTC, hennevogel commented
Timeline:

- 2020-08-27 06:09:29 We rebuild the search indexes as root, which started the searchd as root
- everything was happily working
- 2020-09-03 11:57:17 deployment
- 2020-09-03 11:59:27 noticed that the search service failed to start
- 2020-09-03 12:00:34 noticed a dangling searchd process
- 2020-09-03 12:25:31 tried to fiddle with pid file
- 2020-09-03 12:34:55 noticed wrong permissions on search indexes
- 2020-09-03 12:40:41 we removed the index files, this didn't help
- 2020-09-03 12:47:11 started the searchd service as root, this worked
- 2020-09-03 12:57:27 stoppped the searchd service as root gracefully
- 2020-09-03 12:57:39 started the searchd service with systemd
- 2020-09-03 13:06:53 started reindexing

2020-09-08 13:31 UTC, dmarcoux commented
I got some help from @hennevogel to better investigate and understand what happened. Please have another look.

2020-09-08 14:39 UTC, hennevogel requested changes

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +engine.
```suggestion
On 2020-08-27 we fixed an issue with our search indexes that required us to rebuild them. We did so and everything was running fine. Then on 2020-09-03 we noticed after a deployment that the search service did not start successfully. During our attempt to mitigate this, we destroyed the search indexes again which lead to this service degradation. The search was unavailable for 13 minutes. User visible errors also happened whenever projects and packages where created/updated due to a tight integration of those object with the search engine.
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +We rebuilt the search indices as root on August 27th, 2020 at 8:09 (CEST).
```suggestion
To fix issue [#9436](https://github.com/openSUSE/open-build-service/issues/9436) we rebuilt the search indices August 27th, 2020 at 8:09 (CEST). Unfortunately we ran this command as the user `root`.
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +but it made the searchd process crash.
```suggestion
After deploying on September 3, 2020 at 13:57 (CEST), we noticed that the searchd systemd unit couldn't restart. While trying to mitigate this we removed search indexes (that also had wrong ownership) which caused the searchd service to fail. 
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +
```suggestion
After a while we noticed that there was a searchd process running that was not controlled by the unit.
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +We also had to rebuild the search indices.
```suggestion
- We don't guard ourselves against running "standard" Ruby on Rails commands in production as the wrong user
- Our monitoring for the search service is not sophisticated enough
- The integration of the ActiveRecord callbacks and searchd is too fragile
- We removed search indices without thinking about the consequences
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +- **2020-08-27 08:09**: We rebuild the search indices as root, which created files for search indices as root
```suggestion
- **2020-08-27 08:09**: We rebuild the search indices as root, which started searchd as root and created search indices as that user
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +- Everything was working
```suggestion
- Everything was seemingly working fine. However, the `searchd` systemd unit was failing which we don't monitor. We only monitor for the existence of a process named `searchd`
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +    process crashes. **The search is down**
```suggestion
- **14:34**: We notice wrong file permissions on the search indices and a message about this in the searchd logs
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +- **14:40**: We remove the files for the search indices
```suggestion
- **14:40**: In an desperate attempt, we remove the indices. **The search is down**
```

2020-09-08 14:39 UTC, hennevogel commented on _posts/deployments/2020-09-03-post-mortem.md
> +- **14:57**: We stop the searchd process gracefully
```suggestion
- **14:57**: We stop the searchd process gracefully, which briefly degrades the service again.
```

2020-09-08 16:46 UTC, hennevogel approved these changes

2020-09-08 16:48 UTC, merged