Blogpost of sprint 88
openSUSE/obs-landing pull request #274
Opened 2020-11-27 13:24 UTC by krauselukas

2020-11-27 13:26 UTC, hennevogel commented
Deploy preview for *openbuildservice* ready!

Built with commit c8751a414050c99a56df432932a5d9acde0a742b

https://deploy-preview-274--openbuildservice.netlify.app

2020-11-27 13:41 UTC, hennevogel requested changes

2020-11-27 13:41 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Consensus for the left side navigation
This is a bold claim hehe

2020-11-27 13:41 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +the feedback of our users.
I understand where you are coming from and what you try to explain: Our motivation about doing this now.

But a lede should help me as reader to decide if I want to read on, do I want to spend the 5 minutes of my limited life to read this? See for instance https://writingcooperative.com/a-quick-guide-to-writing-a-better-lede-ff86eb8ed0e

2020-11-27 13:41 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +Thats why we came up with some criterias to decide if we place the action in the left sidebar or not.
This too is a very bold claim :smile: 

As if the decision what to do, was not a decision of taste to a large degree. It sounds *very* defensive and invites questioning IMHO

2020-11-27 13:41 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +us to stay consistent in the future.
Not sure this has anything to do with people getting used to things, remember we are talking beta features here. I think you conflate this with rolling out too much (without rolling it out).

2020-11-27 13:41 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +resources, will stay close to the corresponding represention in the main view.
If you want people to understand, tell them **why** you decided for this. This is the gist of it, the "news", the most important bit.

2020-11-27 13:47 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +the feedback of our users.
As a reader, why you are writing this now, is not really high on my list of concerns. I have 5.000 things to read, why should I read this? What will I know afterward? What will I gain?

2020-11-27 13:48 UTC, vpereira commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Consensus for the left side navigation
we as a team found a consensus.

2020-11-27 13:50 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +resources, will stay close to the corresponding represention in the main view.
Apart from the news that the users need to embrace another set of changes to the navigation in beta of course. Which you also did not really mention.

2020-11-27 13:51 UTC, krauselukas commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Consensus for the left side navigation
hehe, yes I was not to happy myself with it

2020-11-27 13:54 UTC, vpereira commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +Thats why we came up with some criterias to decide if we place the action in the left sidebar or not.
the taste was guided by science and the changes by feedback. So it's for sure more than simple taste.

2020-11-27 13:57 UTC, vpereira commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +us to stay consistent in the future.
we wouldn't revisit it if we didn't receive constructive criticism as feedback. People that couldn't find the actions used daily in their work.

2020-11-27 14:24 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +Thats why we came up with some criterias to decide if we place the action in the left sidebar or not.
"to a large degree" :)

2020-11-27 14:26 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +us to stay consistent in the future.
I'm not sure why you think you need to defend this decision. It's a good decision. Based on feedback, thinking, talking, gut feeling and some 'science'.

Why be defensive about it?

2020-11-27 14:28 UTC, hennevogel commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Consensus for the left side navigation
It sets the tone for the whole piece. I know we struggled with this decision, but why is this important for the people using our app and reading our blog?

2020-11-27 20:17 UTC, vpereira commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +us to stay consistent in the future.
I read it again and I don't see where it is defensive. Instead it talks about how we took the decisions, our reasoning behind it. Because we are writing a blog post, not a change log or anything formal, this shows our readers that it was written by humans and that we care about the other humans reading it.

2020-11-30 11:46 UTC, dmarcoux commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Little drop of consensus
I'm starting to feel like a robot, but here we go. Capitalization has to be fixed in this title and the headings of this post. This can help you: https://capitalizemytitle.com/

2020-11-30 12:46 UTC, krauselukas commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +Thats why we came up with some criterias to decide if we place the action in the left sidebar or not.
I changed the wording a little

2020-11-30 13:03 UTC, krauselukas commented on _posts/development/2020-11-26-consensus-for-the-left-side-navigation.md
> +title: Little drop of consensus
should be fixed now @dmarcoux

2020-11-30 13:05 UTC, krauselukas commented
@hennevogel  @vpereira I rephrased a couple of things, I hope its sound a little less defensive now. I added some reasons in order to explain a little bit why we went with those decisions. Please have another look

2020-11-30 15:59 UTC, krauselukas commented
Commit are squashed and date adjusted, ready to go from my side

2020-12-03 12:20 UTC, hennevogel approved these changes
Now you're selling me somthing, great!

2020-12-03 12:21 UTC, merged