Add blog post for responsive_ux feature rollout
openSUSE/obs-landing pull request #277
Opened 2021-01-12 17:19 UTC by saraycp

Post to announce the changes before the final rollout.

2021-01-12 17:20 UTC, hennevogel commented
:heavy_check_mark: Deploy preview for *openbuildservice* ready!


:hammer: Explore the source changes: ce4229c2e7d7b0eb82396c7277af6549a850344c

:mag: Inspect the deploy logs: [https://app.netlify.com/sites/openbuildservice/deploys/5ffdda3ccdfccc0008c28aac](https://app.netlify.com/sites/openbuildservice/deploys/5ffdda3ccdfccc0008c28aac?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-277--openbuildservice.netlify.app](https://deploy-preview-277--openbuildservice.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-01-12 17:53 UTC, vpereira commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +We encourage you to surf our website from your tablet or smartphone. You will notice the improvements at a glance.
suggestion:
"to surf OBS" instead of "to surf our website"?

2021-01-12 17:53 UTC, vpereira approved these changes

2021-01-12 18:03 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +during the upcoming hours or days.
@saraycp I wouldn't write `hours or days`, maybe just write that it will be rolled out after this blog post is published. To warn the user we can use the status messages and mailing list

2021-01-12 18:09 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +during the upcoming hours or days.
I just simplified the sentence, let me know what you think.

2021-01-12 18:10 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +We encourage you to surf our website from your tablet or smartphone. You will notice the improvements at a glance.
done!

2021-01-12 18:18 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +- In-place edition.
```suggestion
- In-place editing.
```

2021-01-12 18:18 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
Not sure if its more important, I would suggest to go more into direction "another important part"

2021-01-12 18:18 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +during the upcoming hours or days.
I like it :+1:

2021-01-12 18:41 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
"As important as that" ? ;)

2021-01-13 09:25 UTC, danidoni commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
What about `But let's not forget about the work we ...`?

2021-01-13 09:29 UTC, danidoni commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +- https://openbuildservice.org/2020/12/03/revisit-actions-left-side-navigation
I believe this should be clickable urls

2021-01-13 09:31 UTC, danidoni commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
Or better, I would remove the whole sentence, the rest of that paragraph already conveys the idea.

2021-01-13 09:40 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +- https://openbuildservice.org/2020/12/03/revisit-actions-left-side-navigation
True!

2021-01-13 10:25 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
I'm fine with both, I just thought its maybe a bit to much to say its more important :+1:

2021-01-13 11:05 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +- https://openbuildservice.org/2020/12/03/revisit-actions-left-side-navigation
Ok, I've used the real titles for the texts of the links. They look much better now.

2021-01-13 11:05 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
I rephrased the paragraph. What do you think now?

2021-01-13 11:32 UTC, hennevogel requested changes

2021-01-13 11:37 UTC, hennevogel commented
Wouldn't it be simpler if you just call it "responsive navigation" instead of making this artificial difference between new navigation and responsiveness?

I think this would greatly simplify the message.

2021-01-13 11:45 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +But more important than that is the work we have done to convert our interface into a responsive one.
:+1:

2021-01-13 11:51 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +during the upcoming hours or days.
This sentence was changed a few "pushes" ago :smiley:

2021-01-13 11:51 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +We encourage you to surf our website from your tablet or smartphone. You will notice the improvements at a glance.
done

2021-01-13 11:57 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +  <figcaption>Home page with all navigation and without responsiveness</figcaption>
@saraycp what do you mean by `with all navigation`?

2021-01-13 11:58 UTC, saraycp commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +  <figcaption>Home page with all navigation and without responsiveness</figcaption>
ups! I meant "old". Changing....

2021-01-13 12:01 UTC, saraycp commented
> Wouldn't it be simpler if you just call it "responsive navigation" instead of making this artificial difference between new navigation and responsiveness?
> 

But the navigation is not the only thing we have adapted to become responsive.
The user is going to notice many other changes apart from the navigation areas and I want to warn about that.

Anyway, I'll try to simplify or talk about the new navigation inside a "redesigned responsive layout" instead of about "responsive navigation".

2021-01-13 12:08 UTC, krauselukas commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +  <figcaption>Home page with all navigation and without responsiveness</figcaption>
perfect

2021-01-13 13:05 UTC, saraycp commented
@hennevogel, please have a look at the [last changes](https://github.com/openSUSE/obs-landing/compare/89aed4e0208795bef7c7761abaa18413228f8592..7a96c52ada148aad30d82a473dc071f46953a5a5).

2021-01-13 13:26 UTC, hennevogel approved these changes

2021-01-13 13:34 UTC, krauselukas approved these changes

2021-01-13 13:46 UTC, dmarcoux commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +These two images summarize this milestone:
```suggestion
As we say, a picture is worth a thousand words:
```

2021-01-13 13:46 UTC, dmarcoux commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +The navigation areas make the main difference. The top bar includes options closely related to the user like the Profile or his/her Watchlist.
```suggestion
The redesign introduces changes mostly in the navigation areas. The top bar includes links closely related to the user like their profile or their watchlist.
```

2021-01-13 13:46 UTC, dmarcoux commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +The left sidebar contains links to both relevant places inside the web application and general actions.
```suggestion
The left sidebar contains links to both relevant places inside OBS and actions on the current page.
```

2021-01-13 13:46 UTC, dmarcoux commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +Thanks to the valuable feedback provided by the users in our Beta program, we have come up with this solution that tries to provide a more
```suggestion
Thanks to the valuable feedback provided by the users in our beta program, we have come up with this solution that tries to provide a more
```

2021-01-13 13:46 UTC, dmarcoux commented on _posts/development/2021-01-12-responsive-ux-rollout.md
> +As you can see in the blog entries and screenshots, this is not all about navigation. You can perceive many other differences in the redesigned responsive layout. You will find the following changes,
```suggestion
As you can see in the blog entries and screenshots, this is not all about navigation. You will find, among others, the following changes in the redesigned responsive layout:
```

2021-01-13 14:29 UTC, saraycp commented
@dmarcoux your suggestions are addressed too. Please have a look.

2021-01-13 14:29 UTC, dmarcoux approved these changes

2021-01-13 14:30 UTC, merged