Add post for sprint 91 about notifications
openSUSE/obs-landing pull request #282
Opened 2021-02-12 18:46 UTC by saraycp

2021-02-12 18:47 UTC, hennevogel commented
Deploy preview for *openbuildservice* ready!

Built with commit 60b0a64ba8ef11614c851e0a59a90bd445c65088

https://deploy-preview-282--openbuildservice.netlify.app

2021-02-15 11:04 UTC, danidoni commented on _posts/development/2021-02-12-notifications-new-filters.md
> +packages you are involved in. The notifications' filters are there to help you find what you are looking for.
```suggestion
During a normal day, you may receive a big amount of web notifications. The notifications' filters are there to help you find what you are looking for.
```

2021-02-15 11:05 UTC, danidoni commented on _posts/development/2021-02-12-notifications-new-filters.md
> +Attending to the users' feedback, we have introduced a new pair of filters: _Incoming Requests_ and _Outgoing Requests_ filters.
```suggestion
Listening to the users' feedback, we have introduced a new pair of filters: _Incoming Requests_ and _Outgoing Requests_ filters.
```

2021-02-15 11:06 UTC, danidoni commented on _posts/development/2021-02-12-notifications-new-filters.md
> +_Outgoing Requests_ displays all the unread notifications related to requests which were created by yourself.
```suggestion
_Incoming Requests_ displays unread notifications related to Requests that others created in packages where you are involved.
_Outgoing Requests_ displays unread notifications related to requests which were created by yourself.
```

2021-02-15 16:17 UTC, danidoni approved these changes

2021-02-15 18:57 UTC, hennevogel requested changes

2021-02-15 18:57 UTC, hennevogel commented on _posts/development/2021-02-15-notifications-new-filters.md
> +to the rescue, by narrowing down the result' to the once you are looking for.
```suggestion
to the rescue, by narrowing down the result' to the notifications you are looking for.
```

2021-02-15 18:57 UTC, hennevogel commented on _posts/development/2021-02-15-notifications-new-filters.md
> +In previous iterations we've already introduced different notifications' filters.
Please don't talk about things that like `iterations` that don't make sense to anyone but us :)

2021-02-15 18:57 UTC, hennevogel commented on _posts/development/2021-02-15-notifications-new-filters.md
> +Listening to the users' feedback, we have created a new pair of filters: _Incoming Requests_ and _Outgoing Requests_ filters.
```suggestion
Listening to the your feedback, we have created a new pair of filters: _Incoming Requests_ and _Outgoing Requests_ filters.
```

2021-02-16 12:24 UTC, krauselukas commented
@hennevogel please have another look

2021-02-16 13:04 UTC, hennevogel approved these changes

2021-02-16 15:28 UTC, merged