Initial draft for the blog post
openSUSE/obs-landing pull request #299
Opened 2021-06-09 14:33 UTC by danidoni

2021-06-09 14:34 UTC, hennevogel commented
:heavy_check_mark: Deploy Preview for *openbuildservice* ready!


:hammer: Explore the source changes: 96f82b36b09c729f343eb9338157c727580c2202

:mag: Inspect the deploy log: [https://app.netlify.com/sites/openbuildservice/deploys/60c0d1432750200008f4dff6](https://app.netlify.com/sites/openbuildservice/deploys/60c0d1432750200008f4dff6?utm_source=github&utm_campaign=bot_dl)

:sunglasses: Browse the preview: [https://deploy-preview-299--openbuildservice.netlify.app](https://deploy-preview-299--openbuildservice.netlify.app?utm_source=github&utm_campaign=bot_dp)

2021-06-10 07:59 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +title: Improvements Over Continuous Integration with OBS and GitHub/GitLab
```suggestion
title: Improvements for the Continuous Integration with OBS and GitHub/GitLab
```

2021-06-10 07:59 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Build results for repository and architecture
The capitalization is wrong for this title: https://capitalizemytitle.com/

2021-06-10 08:00 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Major SCM Vendors support
Capitalization issues here too: https://capitalizemytitle.com/

2021-06-10 08:00 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Right now we only act on events coming from [GitHub.com](https://github.com) or [GitLab.com](https://gitlab.com).
```suggestion
Right now, we only act on events coming from [GitHub.com](https://github.com) or [GitLab.com](https://gitlab.com).
```

2021-06-10 08:04 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Until now, we were showing only one build result. Now OBS reports the build results back to your PR/MR for each repository and architecture combination of any package.
This paragraph isn't true.

We reported all build results, but only the last one was displayed since we only had one status for all build results. We kept overwriting the status check. There are now one status check per build result, so this is the major difference here.

2021-06-10 08:09 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Build results for repository and architecture
Fixed

2021-06-10 08:09 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Major SCM Vendors support
Fixed

2021-06-10 08:18 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Until now, we were showing only one build result. Now OBS reports the build results back to your PR/MR for each repository and architecture combination of any package.
Okay, what about [this](https://github.com/openSUSE/obs-landing/pull/299/files#diff-e75abc542fb8f3e86a0045bfbf08b9b9d6843c855dda1bc739e465717a98a84cR20)

2021-06-10 08:25 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Until now, we were showing only one build result. Now OBS reports the build results back to your PR/MR for each repository and architecture combination of any package.
This is fine, but the sentence above is still somehow confusing/wrong. This is what I would explain, maybe rephrase it if needed.

We reported all build results, but only the last one was displayed since we only had one status for all build results. We kept overwriting the status check.

2021-06-10 08:40 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Today we have some improvements over our [first attempt at Continuous Integration](https://openbuildservice.org/2021/05/31/scm-integration/).
```suggestion
Today, we have some improvements for our [first iteration at continuous integration](https://openbuildservice.org/2021/05/31/scm-integration/).
```

2021-06-10 08:41 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Introduction
This header should be removed.

```suggestion
```

2021-06-10 08:43 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Until now, we were showing only one build result. Now OBS reports the build results back to your PR/MR for each repository and architecture combination of any package.
Okay, I've reworded it a bit.

2021-06-10 11:28 UTC, hennevogel requested changes

2021-06-10 11:28 UTC, hennevogel commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Today, we have some improvements for our [first iteration at continuous integration](https://openbuildservice.org/2021/05/31/scm-integration/).
The meaning of `iteration` is not what you think for your readers. This is something that makes sense for us in the team, not for anyone else.

2021-06-10 11:28 UTC, hennevogel commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +This will allow you, for example, to rebuild branched packages when pushing new changes to the PR/MR.
You make it sound as if there is more. There isn't right?

2021-06-10 11:28 UTC, hennevogel commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +You maybe had an integration set for a package built against several distributions and architectures. OBS was reporting all build results, but we were showing only the last one on the checks section
integration? What's that? You mean workflow?

2021-06-10 11:28 UTC, hennevogel commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +## Major SCM Vendors Support
You make this sound as if it is a feature. But it's a limitation right? :)

2021-06-10 12:25 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Today, we have some improvements for our [first iteration at continuous integration](https://openbuildservice.org/2021/05/31/scm-integration/).
I disagree with you on this one. Looking at the definition of `iteration`:

> Iteration is the repetition of a process in order to generate an outcome. The sequence will approach some end point or end value. Each repetition of the process is a single iteration, and the outcome of each iteration is then the starting point of the next iteration.

This is what we're doing. What is it for our readers if it's not that?

2021-06-10 12:29 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Today, we have some improvements for our [first iteration at continuous integration](https://openbuildservice.org/2021/05/31/scm-integration/).
I understand `iteration` is internal to our team's working methodology, that our users don't really care. Nevertheless I've changed that sentence so...

2021-06-10 12:32 UTC, danidoni commented
@hennevogel @dmarcoux Review again, please

2021-06-10 12:39 UTC, dmarcoux commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Today, we have some improvements in the Continuous Integration we unveiled in our [last blog post.](https://openbuildservice.org/2021/05/31/scm-integration/).
There is no need to capitalize continuous integration, it's not a proper noun. [I already commented about that earlier](https://github.com/openSUSE/obs-landing/pull/299#discussion_r648976840)

```suggestion
Today, we have some improvements for the continuous integration we unveiled in our [previous blog post](https://openbuildservice.org/2021/05/31/scm-integration/).
```

2021-06-10 15:06 UTC, hennevogel requested changes

2021-06-10 15:06 UTC, hennevogel commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Maybe you had a workflow set for a package built against several distributions and architectures. OBS was reporting all build results, but we were showing only the last one on the checks section of a
I understand what you are trying to say. The OBS shows all build results but the PR only the last one. But this is pretty hard to parse from those sentences. Maybe you can make this a bit simpler?

2021-06-11 09:26 UTC, danidoni commented on _posts/development/2021-06-09-scm-integration-improvements.md
> +Maybe you had a workflow set for a package built against several distributions and architectures. OBS was reporting all build results, but we were showing only the last one on the checks section of a
I've reworded that paragraph. Check it out again, please

2021-06-14 08:42 UTC, merged

2021-06-14 08:51 UTC, dmarcoux commented
It would have been nice to squash the commits before merging... Anyway, it's too late now.