Sprint scm integration
openSUSE/obs-landing pull request #302
Opened 2021-07-01 12:08 UTC by vpereira

2021-07-12 11:08 UTC, hennevogel requested changes

2021-07-12 11:08 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Some OBS projects have dozens of repositories and architecture enabled, but maybe the users just want to have some repositories being reported back to the SCM as status check. Therefore users are goi
```suggestion
Some of your OBS projects probably have dozens of repositories and architectures enabled. But maybe you just want to have some of them reported back to the pull/merge request? Therefore you are now able to limit repositories and architectures using the new filters features.
```

2021-07-12 11:08 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Some OBS projects have dozens of repositories and architecture enabled, but maybe the users just want to have some repositories being reported back to the SCM as status check. Therefore users are goi
And please do not link to the developer wiki. This blog post is the place to tell people how to setup filters.

2021-07-12 11:08 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +title: More Improvements for the Continuous Integration with OBS and GitHub/GitLab
The next one will be `more more improvements`? ;-)

2021-07-12 11:08 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +title: More Improvements for the Continuous Integration with OBS and GitHub/GitLab
```suggestion
title: Reporting filters and on-premise support for continuous integration
```

2021-07-12 11:08 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Limit what we report to the SCM:
```suggestion
## Limit what is reported to the pull/merge request
```

2021-07-12 11:18 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Support private instances from gitlab and github:
> I think the term is `on-premise`

Not really, On-premises is the software or technology that is located within the physical confines of an enterprise often in the company’s data center as opposed to running remotely on hosted servers or in the cloud.

That's not the case here.

2021-07-12 11:23 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Today, users have to make sure that their SCM have SSL well configured using a trusted certificate. The user cannot neither install a custom SSL certificate or ignore it
How a b.o.o user is able to install a root certificate for her self-signed digital certificates to be able to enable OBS to download the `workflows.yml` from her gitlab.example.org? It is not possible, unless the certificate is installed in the operating system layer... 

related: https://github.com/openSUSE/open-build-service/issues/11316

2021-07-12 11:26 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Some OBS projects have dozens of repositories and architecture enabled, but maybe the users just want to have some repositories being reported back to the SCM as status check. Therefore users are goi
> And please do not link to the developer wiki. This blog post is the place to tell people how to setup filters.

Because the whole thing still under development, this blog post will become quite soon out of date, beside that we link quite often our wiki in our posts

2021-07-12 11:27 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +title: More Improvements for the Continuous Integration with OBS and GitHub/GitLab
`on-premise` is not the wrong word here...

2021-07-12 11:31 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Support private instances from gitlab and github:
From gitlab documentation `privately-hosted GitLab instance`

2021-07-12 11:34 UTC, vpereira commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Support private instances from gitlab and github:
other term that comes often - including in the "installer" - is `Self-Hosted`

2021-07-12 11:39 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Support private instances from gitlab and github:
I'm fine with anything that makes the distinction more clear.

2021-07-12 11:40 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Today, users have to make sure that their SCM have SSL well configured using a trusted certificate. The user cannot neither install a custom SSL certificate or ignore it
A b.o.o user can not make the SSL certificate trusted for sure. If you have your own SCM and your own OBS you can.

2021-07-12 11:47 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Some OBS projects have dozens of repositories and architecture enabled, but maybe the users just want to have some repositories being reported back to the SCM as status check. Therefore users are goi
If this blog post gets out of date then we can update it. We have linked a couple of times to the developer wiki when the post was about OBS developer stuff. This is a feature for our customers, not for OBS developers.

2021-07-12 11:49 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Today, based on some new feedback from those of you that enrolled in our [beta program](/2018/10/04/the-beta-program/), we have more improvements for the continuous integration we unveiled in our [pr
Please make sure you also include links to all the other posts in this series. In the other PR they created a partial

https://github.com/openSUSE/obs-landing/pull/304/files#diff-b91ac19286f2f49c0aacacb76f4be0abe661c6a209b7530e67133d9ac551055fR10

2021-07-13 10:20 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Today, users have to make sure that their SCM have SSL well configured using a trusted certificate. The user cannot neither install a custom SSL certificate or ignore it
I still think this warrants an update to the error post about connection problems. If the OBS and the SCM installation can not talk to each other all of this won't work. Reasons they can't talk to each other:

- SSL certificate verification problems
- Network problems
- Private repositories on gitlab

and more possibly...

2021-07-13 10:20 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +## Support private instances from gitlab and github:
self-hosted it is then! I like it.

2021-07-13 11:30 UTC, hennevogel requested changes

2021-07-13 11:30 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +Filters are the way to limit which build results are being reported back to the SCM. Keep in mind that Filters are going to evolute to support many other cases, but for now, we reduced the scope to a
```suggestion
Filters are the way to limit which build results are being reported back to the SCM. Keep in mind that Filters are going to evolve to support many other cases, but for now, we reduced the scope to architectures and repositories only.
```

2021-07-13 11:30 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-more-improvements.md
> +`only` and `ignore` are your tools to control what and what not are going to be reported back as status check.
```suggestion
`only` and `ignore` are your tools to control what and what not are going to be reported back as status check. Only has precedence over ignore, so if both are defined, ignore is not considered.
```

2021-07-13 11:43 UTC, hennevogel approved these changes

2021-07-13 11:55 UTC, merged