Document common errors that users made in SCM integration
openSUSE/obs-landing pull request #303
Opened 2021-07-08 11:05 UTC by rubhanazeem

2021-07-08 11:28 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +title: More Improvements for the Continuous Integration with OBS and GitHub/GitLab
How about this title to avoid repeating the title from our previous blog post?

```suggestion
title: Common Pitfalls to Avoid in the Continuous Integration with OBS and GitHub/GitLab
```

2021-07-08 11:30 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +# Introduction
This heading doesn't bring any context or value, we can remove it.

```suggestion
```

2021-07-08 11:35 UTC, rubhanazeem commented on _posts/development/2021-07-08-document-scm.md
> +title: More Improvements for the Continuous Integration with OBS and GitHub/GitLab
Done.

2021-07-08 11:35 UTC, rubhanazeem commented on _posts/development/2021-07-08-document-scm.md
> +# Introduction
Done.

2021-07-08 11:42 UTC, saraycp requested changes

2021-07-08 11:42 UTC, saraycp commented on _posts/development/2021-07-08-document-scm.md
> +This article is the continuation of [Continuous Integration with OBS and GitHub/GitLab](https://openbuildservice.org/2021/05/31/scm-integration/). Here we have explained some tips that were not clear
```suggestion
This article is the continuation of a series of articles related to the SCM integration, starting with [Continuous Integration with OBS and GitHub/GitLab](https://openbuildservice.org/2021/05/31/scm-integration/). Here we explain some tips that were not clear in other posts.
```

2021-07-08 11:57 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +## Structure of the repository in SCM ##
Ending a heading with `#` isn't needed. The capitalization is also wrong. You can check it with https://capitalizemytitle.com/.

```suggestion
## Structure of the Repository in SCM
```

2021-07-08 12:06 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +OBS assumes that your repository contains a `.obs/workflow.yml` file. To get the idea of how to format the workflow.yml file you can see the sample [here](https://github.com/openSUSE/open-build-servi
```suggestion
OBS downloads from the default branch (often called `main` or `master`) of your SCM repository the workflow configuration file which is to be stored in `.obs/workflows.yml`. Any change to this file on other branches won't be taken into account. For a workflow configuration file example, have a look [here](https://github.com/openSUSE/open-build-service/tree/master/.obs/workflows.yml).
```

2021-07-08 12:07 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +## Package in OBS (_service file) ##
```suggestion
## The _service File
```

2021-07-08 12:11 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +## Personal Access Token ##
This section is already explained in the first blog post about the OBS/SCM integration: https://openbuildservice.org/2021/05/31/scm-integration/#authentication-setup

2021-07-08 12:11 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +## Creating Workflow tokens in OBS ##
This section is already explained in the first blog post about the OBS/SCM integration: https://openbuildservice.org/2021/05/31/scm-integration/#authentication-setup, so it's redundant. We can link to that blog post instead of repeating ourselves.

2021-07-08 15:09 UTC, danidoni commented on _posts/development/2021-07-08-document-scm.md
> +Many of you are already playing around with our new beta feature: Souce code management system (SCM) integration with OBS.
```suggestion
Many of you are already playing around with our new beta feature: Source Code Management system (SCM) integration with OBS.
```
What about using just the SCM acronym?

2021-07-08 17:51 UTC, dmarcoux commented on _posts/development/2021-07-08-document-scm.md
> +OBS assumes that your repository contains a `.obs/workflow.yml` file. To get the idea of how to format the workflow.yml file you can see the sample [here](https://github.com/openSUSE/open-build-servi
It's `workflows.yml`:

```suggestion
OBS assumes that your repository contains a `.obs/workflows.yml` file. To get the idea of how to format the workflows.yml file you can see the sample [here](https://github.com/openSUSE/open-build-service/tree/master/.obs). OBS only considers this file to be present in your base branch and will not consider any updates to this file in other branches.  
```

2021-07-09 15:33 UTC, saraycp commented
After the feedback we received, we decided to re-write the whole post. For that, we are going to close this PR in favour of #304 which is more "pitfalls oriented" :)

2021-07-09 15:33 UTC, closed without merging