Add post for common pitfalls in the SMC integration
openSUSE/obs-landing pull request #304
Opened 2021-07-09 15:29 UTC by saraycp

Co-authored-by: Rubhan Azeem <rubhan.azeem@suse.com>

2021-07-12 07:34 UTC, dmarcoux commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +Check these blog posts to find complete instructions about the SCM integration in OBS:
```suggestion
Check out these blog posts to find complete instructions about the SCM integration in OBS:
```

2021-07-12 07:35 UTC, dmarcoux commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +- [Improvements for the Continuous Integration with OBS and GitHub/GitLab](https://openbuildservice.org/2021/06/14/scm-integration-improvements/)
These blog posts should be ordered by publishing date, it's not the case right now.

2021-07-12 07:40 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +Here you have a list of common pitfalls and their possible solutions.
It reads better and it's shorter. I removed possible because it sounds like what we wrote might not solve the issues, although we're pretty sure it is.
```suggestion
Here's a list of common pitfalls and their solutions.
```

2021-07-12 07:42 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +This SCM integration feature is only available for users in Beta Program. Please join the Beta Program in OBS to be able to use this new feature.
```suggestion
This SCM integration feature is only available for users in the beta program. Please [join the beta program](/2018/10/04/the-beta-program/) in OBS to be able to use this new feature.
```

2021-07-12 07:52 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +To get the idea of how to format the `.obs/workflows.yml` file you can see the sample [here](https://github.com/openSUSE/open-build-service/tree/master/.obs). You can find some guidelines in this art
Let's point directly to the file since this is what users want to see:
```suggestion
To get an idea of how to format the `.obs/workflows.yml` file, you can see a sample [here](https://github.com/openSUSE/open-build-service/tree/master/.obs/workflows.yml). You can find some guidelines in this article:
```

2021-07-12 07:52 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +[Continuous Integration with OBS and GitHub/GitLab](https://openbuildservice.org/2021/05/31/scm-integration/).
Please use relative URLs for all links across the blog post:
```suggestion
[Continuous Integration with OBS and GitHub/GitLab](/2021/05/31/scm-integration/).
```

2021-07-12 07:53 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +In the configuration file, `.obs/workflows.yml`, you have to specify the name of the project and package you want to connect with the SCM.
Unneeded comma:
```suggestion
In the configuration file `.obs/workflows.yml`, you have to specify the name of the project and package you want to connect with the SCM.
```

2021-07-12 11:51 UTC, dmarcoux commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +- [Common Pitfalls to Avoid in the Continuous Integration with OBS and GitHub/GitLab](/2021/07/12/scm-integration-pitfalls/)
Having this link here is a bit confusing since this is pointing to the blog post in which it's included. I wonder now if we should go perhaps with something like the partial we had for the [Revamping UI blog posts](https://github.com/openSUSE/obs-landing/blob/master/_includes/partials/_revamping-ui-releases-history.md). It's nicer than a list of links and we can include the partials in every blog posts of the SCM/OBS integration.

What do you think?

2021-07-12 11:52 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +  <figcaption>Github Webhook Errors</figcaption>
```suggestion
  <figcaption>GitHub Webhook Errors</figcaption>
```

2021-07-12 11:53 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +  <figcaption>Gitlab Webhook Errors</figcaption>
```suggestion
  <figcaption>GitLab Webhook Errors</figcaption>
```

2021-07-12 11:54 UTC, hennevogel requested changes

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +**Error message:** *"You are not authorized to create this Token/workflow."*
This is not going to be in the webhook request cycle right?

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +OBS assumes that your repository contains a `.obs/workflows.yml` file. OBS only considers this file to be present in your default branch (i.e master or main) and will not consider any updates to this
```suggestion
The feature requires that your SCM repository contains a `.obs/workflows.yml` file. OBS only considers this file in your default branch (i.e master or main) and will not consider this file in other branches or forks.
```

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +OBS assumes that your repository contains a `.obs/workflows.yml` file. OBS only considers this file to be present in your default branch (i.e master or main) and will not consider any updates to this
I will see the same error if the file isn't accessible for any other reasons right?

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +Don't forget to provide your SCM personal access token when you create an OBS workflow token.
You can't forget this, it's validated. If you get this error, it's invalid credentials. What do I have to do to get out of this situation?

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can check a sample of `_service` file published on [OBS](https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_service?expand=0&rev=424295e96102d316454e624b0a3d1ae3)
This makes it sounds as if reporting depends on using obs-service-tar_scm. But packages without a _service file will be branched, build and the result will be reported.

2021-07-12 11:54 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
A package can not build for many more reasons. Maybe something generic like your package never built? And how do I get out of this situation?

2021-07-12 11:54 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +See how [here](https://openbuildservice.org/2018/10/04/the-beta-program/).
This sentence isn't needed anymore now that we have the `join the beta program` link in the previous sentence.
```suggestion
```

2021-07-12 12:03 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +OBS assumes that your repository contains a `.obs/workflows.yml` file. OBS only considers this file to be present in your default branch (i.e master or main) and will not consider any updates to this
Yes, the error message will be the same.

2021-07-12 12:08 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +Don't forget to provide your SCM personal access token when you create an OBS workflow token.
ATM the only option the user has to create a token is using OSC. Users can create a new token but once we have UI options available for users where they can edit their token, that will be easier and users can replace invalid SMC tokens with the valid ones.

2021-07-12 12:10 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +**Error message:** *"You are not authorized to create this Token/workflow."*
If I remember correctly, this is the exact error received in the webhook.

2021-07-12 12:15 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can check a sample of `_service` file published on [OBS](https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_service?expand=0&rev=424295e96102d316454e624b0a3d1ae3)
Sure, OBS will still build and report, but the build won't include the source changes if a `_service` file isn't present. Workflows are pretty useless without this.

2021-07-12 12:29 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +**Error message:** *"You are not authorized to create this Token/workflow."*
okay 👍🏿

2021-07-12 12:30 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +Don't forget to provide your SCM personal access token when you create an OBS workflow token.
But we don't so you should tell people that they will have to delete the old one, create a new one with good credentials.

2021-07-12 12:32 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +Don't forget to provide your SCM personal access token when you create an OBS workflow token.
Okay, sure.

2021-07-12 12:34 UTC, hennevogel requested changes

2021-07-12 12:34 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can check a sample of `_service` file published on [OBS](https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_service?expand=0&rev=424295e96102d316454e624b0a3d1ae3)
You are right maybe, depends a bit on your package and the services includes, but that's not the point, correct?

The point is of this section is: The Package Doesn't Build. While it does build (but not the things you would maybe expect it to build).

2021-07-12 13:59 UTC, dmarcoux commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +There is a lot more to come. We'll keep you updated with all new updates._
I would remove this sentence, it's not needed. Don't forget to put back the `_` at the end of the paragraph.
```suggestion
```

2021-07-12 13:59 UTC, dmarcoux commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +
This empty line can be removed.
```suggestion
```

2021-07-12 14:02 UTC, rubhanazeem commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +There is a lot more to come. We'll keep you updated with all new updates._
Done

2021-07-12 14:03 UTC, rubhanazeem commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +
Done

2021-07-12 14:03 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can check a sample of `_service` file published on [OBS](https://build.opensuse.org/package/view_file/OBS:Server:Unstable/obs-server/_service?expand=0&rev=424295e96102d316454e624b0a3d1ae3)
Alright, I've updated that section.

2021-07-12 15:36 UTC, saraycp commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
This section is no-longer part of `The Package Doesn't Build`, this is now an independent section.
This is the problem we faced in the manual tests. We can always add new building problems and solutions in the future.

Is it ok for you if we leave it like it is?

@hennevogel

2021-07-12 15:48 UTC, rubhanazeem commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +moved on to the [Improvements for the Continuous Integration with OBS and GitHub/GitLab](/2021/06/14/scm-integration-improvements/) in June 2021._
done.

2021-07-12 15:48 UTC, rubhanazeem commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +_We started off with the [Continuous Integration with OBS and GitHub/GitLab](/2021/05/31/scm-integration/) in May 2021,
done.

2021-07-12 15:56 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
It's very confusing IMHO. Now so even more because I don't know which project/package you are talking about. The source or the target?

2021-07-12 16:03 UTC, hennevogel requested changes

2021-07-12 16:03 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
```suggestion
### No build result updates arrive your PR/MR

If a package can't be build for any of the many reasons a package in the OBS can't be build then the status of the check in your pull/merge request will never change. Some of the more frequent ones are:

- A build is unresolvale
- A build is broken
- No repositories defined on your source project

You should check the project directly on OBS and [help each other](/support) with problems.
```

2021-07-12 16:03 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
Made a suggestion

2021-07-12 16:09 UTC, saraycp commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +You can add them in the Repositories tab of the package's project page.
@hennevogel applied, thanks!

2021-07-12 16:22 UTC, hennevogel requested changes

2021-07-12 16:22 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +## Where to See the Errors?
Okay only one thing missing to make this more readable IMHO. Put this section to the bottom and add a sentence like:

`Some errors you will also see in your pull/merge request or in OBS itself.`

2021-07-12 16:23 UTC, hennevogel commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +OBS assumes that your repository contains a `.obs/workflows.yml` file. OBS only considers this file to be present in your default branch (i.e master or main) and will not consider any updates to this
You should mention this.

2021-07-12 16:35 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +## Where to See the Errors?
Done.

2021-07-12 17:46 UTC, krauselukas approved these changes
@saraycp @rubhanazeem I like it :) well done!

2021-07-12 18:11 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +### No build result updates arrive your PR/MR
To fix the capitalization and a missing `In`:
```suggestion
### No Build Result Updates Are Displayed in Your PR/MR
```

2021-07-12 18:12 UTC, dmarcoux commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +If a package can't be build because of one of the many reasons a package in the OBS can't be build, then the status of the check in your pull/merge request will never change. Some of the more frequen
```suggestion
If somehow a package can't be build, then the status of the check in your pull/merge request will never change. Some of the more frequent causes of packages not building are:
```

2021-07-13 07:17 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +### No build result updates arrive your PR/MR
Done.

2021-07-13 07:18 UTC, rubhanazeem commented on _posts/development/2021-07-12-scm-integration-pitfalls.md
> +If a package can't be build because of one of the many reasons a package in the OBS can't be build, then the status of the check in your pull/merge request will never change. Some of the more frequen
Done.

2021-07-13 07:53 UTC, dmarcoux approved these changes
Great work @rubhanazeem and @saraycp!

2021-07-13 08:36 UTC, hennevogel approved these changes

2021-07-13 08:37 UTC, merged