Sprint 111 blog post
openSUSE/obs-landing pull request #342
Opened 2022-02-03 15:23 UTC by rubhanazeem

2022-02-03 16:29 UTC, hennevogel requested changes

2022-02-03 16:29 UTC, hennevogel commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +In November 2021, we introduced [workflow runs and more](/2021/11/22/scm-workflow-runs). Now, we have made [UI and reporting improvements](/2022/02/03/scm-integration-report-improvements)._
Now is gone. And again. And again! 😉 

It helps to just always use the month....

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Today, we have some improvements around UI and reporting and user feedback for the continuous integration we unveiled in ours [previous blog post](https://openbuildservice.org/2021/05/31/scm-integrat
```suggestion
Today, we have some improvements around UI and reporting and user feedback for the continuous integration we unveiled in our [previous blog post](https://openbuildservice.org/2021/05/31/scm-integration/).
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +## WorkflowRuns artifacts
```suggestion
## Artifact of Workflow Runs
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +A single webhook can generate different artifacts on OBS. Artifacts are the projects or packages that are involved in the step definition given in `workflows.yml`.
```suggestion
A single webhook on your SCM can trigger different workflows, given in `workflows.yml`, to run. Each Workflow Run will most likely generate some changes inside OBS project or packages. Those changes are what we call Workflow Run Artifacts. ```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +After each workflow run, we now display all the artifacts involved so you can better understand what was going on.
```suggestion
After each workflow run, we now display all the artifacts involved so you can better understand and debug what was going on.
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +For example, repositories and architectures if the step is `configure_repositories` or projects and packages in steps like `link_package` etc.
```suggestion
For example, repositories created if the step is `configure_repositories` or projects and packages created in steps like `link_package` etc.
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Please refer to the [documentation](https://github.com/openSUSE/open-build-service/wiki/Better-SCM-CI-Integration#set-flags) to learn more.
This is the developer documentation, the user documentation is in the books.

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Projects and packages can have different flags based on repositories and architectures. With `set_flags` you have the opportunity to manage flags for your
I think you should explain a bit what this is about. Steal from the user docu 😃

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +## Improvement for WorkflowRuns UI
```suggestion
## Improvement for Workflow Runs User Interface
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +To make easier to debug and troubleshoot broken SCM integrations we have updated the `WorkflowRuns UI`.
```suggestion
So to make it easier to debug and troubleshoot broken SCM integrations we have added some more feature to the Workflow Runs UI.
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +WorkflowRuns is one of the most important places to debug your workflows. It helps you to fix the problems like the wrong configurations in `workflows.yml`.
```suggestion
The Workflow Runs page is the most important place to debug your workflows. It helps you to fix the problems like the wrong configurations in `workflows.yml`.
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +- A new show view for individual workflows has been added to help you share WorkflowRuns across your team.
```suggestion
- A new show view for individual workflows has been added to help you share Workflow Runs across your team.
```

2022-02-03 16:29 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +- New filter options to help filter WorkflowRuns based on `status` and `event type`
```suggestion
- New filter options to help filter Workflow Runs based on `status` and `event type`
```

2022-02-03 16:32 UTC, dmarcoux commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +A single webhook can generate different artifacts on OBS. Artifacts are the projects or packages that are involved in the step definition given in `workflows.yml`.
In addition to @hennevogel's proposal, we should refer to `.obs/workflows.yml` instead of `workflows.yml`.

2022-02-04 09:53 UTC, danidoni commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +In November 2021, we introduced [workflow runs and more](/2021/11/22/scm-workflow-runs). Now, we have made [UI and reporting improvements](/2022/02/03/scm-integration-report-improvements)._
Also, I find a the text `...At the beginning of November 2021 [...] In November 2021 [...]` redundant. I would merge the last two paragraphs together.

2022-02-04 14:35 UTC, hennevogel requested changes

2022-02-04 14:35 UTC, hennevogel commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Today, we have some improvements around UI and reporting and user feedback for the continuous integration we unveiled in our [previous blog post](https://openbuildservice.org/2021/05/31/scm-integrati
```suggestion
Today, we have some improvements around the continuous integration we unveiled in our [previous blog post](https://openbuildservice.org/2021/05/31/scm-integration/). We expanded the workflow run interface, added a new type of step to configure repository flags and introduced a breaking change to the configure_repositories step.
```

2022-02-07 10:05 UTC, danidoni commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +## Artifact of Workflow Runs
```suggestion
## Artifacts of Workflow Runs
```

2022-02-07 10:05 UTC, danidoni commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +## Artifact of Workflow Runs
or
```suggestion
## Workflow Runs Artifacts
```

2022-02-07 11:02 UTC, saraycp requested changes

2022-02-07 11:02 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +- A new show view for individual workflows has been added to help you share Workflow Runs across your team.
The show view is still not shareable with someone else, so I would change the text a bit:

```suggestion
- The details about each workflow run are displayed on a new page.
- Together with the Request and Response, we added the new tab Artifacts.
```

2022-02-07 11:04 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +## Artifact of Workflow Runs
Well, Dani's suggestion sounds better: "Workflow Runs Artifacts"

 https://github.com/openSUSE/obs-landing/pull/342#discussion_r800494214

2022-02-07 11:48 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +  <img src="/images/posts/sprint_111_workflow_runs_show.png" alt="Workflow runs show view" />
Sorry, I didn't realize before... this screenshot doesn't contain the Artifacts tab.
You can use this one instead:
https://openbuildservice.org/help/manuals/obs-user-guide/images/workflow_runs_request.png

2022-02-07 11:48 UTC, danidoni commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Example of artifacts for a push event:
```suggestion
```

2022-02-07 11:48 UTC, danidoni commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +  <figcaption>Workflow run artifacts</figcaption>
```suggestion
  <figcaption>Workflow run artifacts for a push event</figcaption>
```

2022-02-07 11:53 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +- The details about each workflow run are displayed on a new page.
```suggestion
So to make it easier to debug and troubleshoot broken SCM integrations we have added some more features to the Workflow Runs UI:

- The details about each workflow run are displayed on a new page.
```

Here I suggest finishing the first paragraph with `:` and removing "You will get details like:".

2022-02-07 12:26 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +You already know about the `configure_repositories` step. Until now a single path element is defined per repository configured, but we realized for some projects more than one path has to be defined.
One last thing :innocent: 

In the introduction, you mentioned that there is a breaking change. However, in the body it's not clear which is the breaking one.

Probably a little change like this is enough:

 ```suggestion
You already know about the `configure_repositories` step. Until now a single path element is defined per repository configured, but we realized for some projects more than one path has to be defined. So, we have made improvements for the support of multiple path elements. The breaking change has been documented and you can check it out [here](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.obs_workflows.steps.configure_repositories_architectures_for_a_project).
```

2022-02-07 12:29 UTC, saraycp commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +You already know about the `configure_repositories` step. Until now a single path element is defined per repository configured, but we realized for some projects more than one path has to be defined.
You can even have something more evident like:

:warning: Breaking change :warning: 
Check the documentation [here](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html#sec.obs.obs_scm_ci_workflow_integration.obs_workflows.steps.configure_repositories_architectures_for_a_project) and adapt your _configure_repositories_ step in your `.obs/workflows.yml`

2022-02-07 12:42 UTC, saraycp approved these changes

2022-02-07 13:58 UTC, danidoni commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Example of artifacts for a push event:
I would remove this line as suggested, because it's redundant with the caption of the image below...

2022-02-07 14:11 UTC, rubhanazeem commented on _posts/development/2022-02-03-scm-integration-report-improvements.md
> +Example of artifacts for a push event:
It's removed.

2022-02-07 14:36 UTC, danidoni approved these changes

2022-02-07 14:42 UTC, hennevogel approved these changes

2022-02-07 14:43 UTC, merged