Add post-mortem of May 31th
openSUSE/obs-landing pull request #364
Opened 2022-05-31 11:22 UTC by saraycp

About the `rack` gem version mismatch.

2022-05-31 13:32 UTC, hennevogel requested changes

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +```
I don't think this is the root cause, this is only part of what happened. 

The root cause is that we had different `rack` versions installed in the system and the bundle. Similar to the `strscan` incident.

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +Merging and deploying the `rack` gem update.
Deployment was the trigger.

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +The server was down for too long.
That always is wrong in an incident, I don't think it's worth mentioning. Here are some other things I think went wrong.

- We did not resolve all the action items from the `strscan` incident yet (might have saved us)
- We had a handover for DemolitionSquad on Monday (A->B) and on Tuesday (B-A) that didn't go well
- We did not block deployment (technically) even though we were aware of the problem

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:37 Detect the server is down.
hm 4 minutes? Really?

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:40 Receive alerts from our monitoring system.
This also seems off. It took 7 minutes to receive an alert?

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:44 Inform on different channels.
```suggestion
- 08:44 We informed people on different channels
```

2022-05-31 13:32 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:58 Change the rack gem version on Gemfile.lock and restart Apache. This doesn't solve the problem.
This did solve the problem. We just did not wait long enough I think.

2022-05-31 15:09 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:37 Detect the server is down.
I added another item to the list to be more precise.

- Deployment started at 08:33
- we got the error in the output of `ansible-obs` at 08:35
- around 08:36/08:37 I took some screenshots of the output, checked the whole output trying to understand the error, and tried to access OBS which was down.
- we received the alerts at 08:40, the reason is that the alert checks if we are over/under the limit for 5 mins.

I attach two screenshots to demonstrate what I explain:

![Screenshot from 2022-05-31 16-47-53](https://user-images.githubusercontent.com/2581944/171207182-707e64e7-7c39-4949-ae9c-5aef4659b6ba.png)

![Screenshot 2022-05-31 at 16-46-43 Passenger - Grafana](https://user-images.githubusercontent.com/2581944/171207148-038b0841-99ba-4f7b-aaae-17835971d9fe.png)

2022-05-31 15:22 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:37 Detect the server is down.
Okay then we have another TODO. We need a shorter alerting timeframe.

2022-05-31 15:25 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:58 Change the rack gem version on Gemfile.lock and restart Apache. This doesn't solve the problem.
Rephrased

2022-05-31 15:25 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +The server was down for too long.
I omit the second point in the post-mortem, we already talked about that in the Retro meeting. Of course, this is important and we have to do our best in this regard, but I think that's a team matter, not interesting for the people reading the post-mortem.

2022-05-31 15:25 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +```
Rephrased.

2022-05-31 16:06 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:37 Detect the server is down.
> Okay then we have another TODO. We need a shorter alerting timeframe.

I'm going to reduce the timeframe of the alerts involved in this case. I can change it from 5mins to 2mins maybe and we'll see if it is too much.

2022-05-31 16:25 UTC, hennevogel commented
Pushed something on top

2022-05-31 16:26 UTC, hennevogel requested changes

2022-05-31 16:26 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:35 Deployment failed.
Another question I have. *What* exactly failed here?

2022-06-01 08:47 UTC, saraycp commented on _posts/deployments/2022-05-31-post-mortem.md
> +-
I added a commit on top for this, it should be squashed.

2022-06-01 08:54 UTC, saraycp commented
@hennevogel I added some commits on top, they should be squashed before merging.

2022-06-01 10:29 UTC, hennevogel commented on _posts/deployments/2022-05-31-post-mortem.md
> +- 08:35 Deployment failed.
Okay so this and the next event in the timeline is the same thing.

2022-06-01 11:21 UTC, hennevogel commented
@saraycp I squashed things, can you check again?

2022-06-01 11:21 UTC, hennevogel approved these changes

2022-06-01 12:50 UTC, merged