Add blog post for sprint 123
openSUSE/obs-landing pull request #370
Opened 2022-08-12 11:34 UTC by rubhanazeem

Signed-off-by: Rubhan Azeem <rubhanazeem@gmail.com>

2022-08-12 12:00 UTC, saraycp requested changes

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +title: BsRequest Workflow Redesign
`BsRequest` is an internal concept, something users might not know about.

I wouldn't use "workflow" either, we already use that word a lot when talking about SCM/CI integration.

What about?

```suggestion
title: Request Page Redesign
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We are continuously trying to improve OBS and finding new ways to improve the efficiency of our users. Keeping this in mind, we are back with the updates in the BsRequest workflow. There is still a l
Redundant `improve`.

```suggestion
We are continuously trying to improve OBS and finding new ways to enhance the efficiency of our users. Keeping this in mind, we are back with a new proposal for the request page. There is still a long way to go but expect to see many more updates in the coming weeks. Without further ado, here you are the work-in-progress request page redesing.
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +## Restructuring of the BsRequest show page
```suggestion
## Restructuring of the Request Show Page
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +This redesign presents different pieces of information in its container. We have broken down the single page into multiple components. Now you have information about the request divided into four par
```suggestion
This redesign presents different pieces of information. We have broken down the single page into multiple components. Now you have information about the request divided into four parts: Overview, Build Results, Changes, and Mentioned issues.
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +## Merging comments and history
```suggestion
## Merging Comments and History
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +## Presentation of open, accepted, and declined reviews
```suggestion
## Presentation of Open, Accepted, and Declined Reviews
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We realised it wasn't easy to track the progress on the reviews. We have simplified reviews summary to present them in such a way that users understand easily about the state of the requested reviews
```suggestion
We realised it wasn't easy to track the progress of the reviews, so we present them in a way that helps users understand the state of the requested reviews easily.
```

2022-08-12 12:00 UTC, saraycp commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +## Making decision on the request
```suggestion
## Making a Decision on the Request
```

2022-08-12 12:59 UTC, hennevogel requested changes

2022-08-12 12:59 UTC, hennevogel commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We have now merged the comments and history elements. They are presented in chronological order as a single list. It will help users to follow the conversations and the events that happened in the re
```suggestion
We merged the comments and history into one chronological list. We think it will help you to follow the course of the requests' history better if they are presented together.
```

2022-08-12 12:59 UTC, hennevogel commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +This redesign presents different pieces of information in its container. We have broken down the single page into multiple components. Now you have information about the request divided into four par
Not quite sure what you are trying to say with "components". That we have different tabs?

2022-08-12 12:59 UTC, hennevogel commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We realised it wasn't easy to track the progress on the reviews. We have simplified reviews summary to present them in such a way that users understand easily about the state of the requested reviews
users == you

2022-08-12 13:01 UTC, hennevogel commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +This redesign presents different pieces of information in its container. We have broken down the single page into multiple components. Now you have information about the request divided into four par
I very much like that you tell people *why* we changed it this way. Can you also do this for this section? Why did we split this into the "new" tabs?

2022-08-15 08:09 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We are continuously trying to improve OBS and finding new ways to improve the efficiency of our users. Keeping this in mind, we are back with the updates in the BsRequest workflow. There is still a l
Improving/Enhancing the efficiency of someone sounds weird.

2022-08-15 08:14 UTC, rubhanazeem commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +title: BsRequest Workflow Redesign
Done.

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We are continuously trying to improve OBS and finding new ways to enhance the efficiency of our users. Keeping this in mind, we are back with a new proposal for the request page. There is still a lon
Improving/Enhancing the efficiency of someone sounds weird, almost like if our users were machines. Please rephrase this.

There is also a small typo:
```suggestion
We are continuously trying to improve OBS and finding new ways to enhance the efficiency of our users. Keeping this in mind, we are back with a new proposal for the request page. There is still a long way to go but expect to see many more updates in the coming weeks. Without further ado, here you have the work-in-progress request page redesign.
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +## Restructuring of the Request Show Page
To be consistent with this blog post's title:
```suggestion
## Restructuring of the Request Page
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +This redesign presents different pieces of information. We have broken down the single page into multiple tabs. Now you have information about the request divided into four parts: Overview, Build Res
```suggestion
This redesign presents different pieces of information. We have broken down the single page into multiple tabs. Now, you have information about the request divided into four parts: Overview, Build Results, Changes, and Mentioned Issues.
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We proposed this change because we want users to have clear and broader idea about the request. We think separate place for every piece of information gives you clear understanding and you don't have
```suggestion
We proposed this change for you to have clear and broader idea about the request. We think separate place for every piece of information gives you clear understanding and you don't have to scroll through the page to find something.
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We merged the comments and history into one chronological list. We think it will help you to follow the course of the requests' history better if they are presented together.
```suggestion
We merged the comments and history into one chronological list. We think it will help you follow the course of the request's history better if they are presented together.
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We realised it wasn't easy to track the progress of the reviews, so we present them in a way that helps you to understand the state of the requested reviews easily.
```suggestion
We realised it wasn't easy to track the progress of the reviews, so we present them in a way that helps you to easily understand the state of the requested reviews.
```

2022-08-15 08:37 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We have also proposed changes on approving/declining the requests. To make a decision on a requested review, you have a clear indication for which user you want to give a review. Here are some screen
It's not always going to be a user, so I would mention the various entities:
```suggestion
We have also proposed changes on approving/declining requests. To make a decision on a requested review, you have a clear indication for whom you're giving the review, being a user, a group, a project or a package. Here are some screenshots;
```

2022-08-15 08:39 UTC, dmarcoux commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +We proposed this change because we want you to have clear and broader idea about the request. We think separate place for every piece of information gives you clear understanding and you don't have t
```suggestion
We proposed this change for you to have clear and broader idea about the request. We think separate place for every piece of information gives you clear understanding and you don't have to scroll through the page to find something.
```

2022-08-15 09:27 UTC, dmarcoux commented
I pushed to fix some small typos.

2022-08-15 09:27 UTC, dmarcoux approved these changes

2022-08-15 11:06 UTC, hennevogel commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +This redesign presents different pieces of information in its container. We have broken down the single page into multiple components. Now you have information about the request divided into four par
I reworded this now...

2022-08-15 11:20 UTC, hennevogel approved these changes
I gave my review through pushes...

2022-08-15 11:34 UTC, dmarcoux commented
With the renaming of `Overview` to `Conversation`, we will have to redo the screenshots where this is visible.

2022-08-15 12:22 UTC, krauselukas commented on _posts/development/2022-08-12-request-workflow-redesign.md
> +Now it was time to take on the the level boss, redesigning the page where nearly all of the collaboration in OBS happens: the Request page.
```suggestion
Now it was time to take on the the boss level, redesigning the page where nearly all of the collaboration in OBS happens: the Request page.
```

2022-08-15 12:26 UTC, krauselukas commented
Nice blog post!

2022-08-15 12:28 UTC, dmarcoux commented
Screenshots updated to include the renaming of the Overview tab to Conversation.

2022-08-15 12:53 UTC, krauselukas approved these changes

2022-08-15 14:43 UTC, krauselukas approved these changes

2022-08-15 14:56 UTC, merged