Blog post SCM/CI integration roll-out announcement
openSUSE/obs-landing pull request #374
Opened 2022-09-20 10:02 UTC by saraycp

Can't be merged until the last changes are deployed.

2022-09-20 10:48 UTC, danidoni commented
LGTM

2022-09-20 11:30 UTC, hennevogel requested changes
I'm missing a high level description of the feature.

2022-09-20 11:30 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +ready to roll it out for every single user in OBS.
```suggestion
ready today to push it out of the beta program, making it generally available in OBS.
```

2022-09-20 11:30 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +OBS and different SCMs. Thanks to the valuable feedback we received from users
```suggestion
In May of 2021 we took our first steps towards putting OBS builds into the continuous integration cycle with the SCM/CI feature. Thanks to the valuable feedback we received from users
```

2022-09-20 11:30 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +title: SCM/CI Integration in OBS, a Definitive Feature
```suggestion
title: General availability of the SCM/CI Integration feature
```

2022-09-20 13:01 UTC, saraycp commented
@hennevogel  I introduced your suggestions and added an extra first section describing the feature a bit.

Please have another look.

2022-09-20 13:34 UTC, hennevogel requested changes

2022-09-20 13:34 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +and then, you can integrate those sources with OBS to run different workflows.
```suggestion
With the SCM/CI feature you can take advantage of source code management (SCM) systems like GitHub or GitLab to manage your package sources and integrate OBS to run different continuous integration workflows.
```

2022-09-20 14:23 UTC, hennevogel requested changes

2022-09-20 14:23 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +
I would add another screenshot of the github side. Like

![Screenshot from 2022-09-20 16-23-16](https://user-images.githubusercontent.com/514785/191283842-d14fe6e3-f7c8-4fa7-9268-39d9ce886a40.png)

2022-09-20 14:25 UTC, hennevogel requested changes

2022-09-20 14:25 UTC, hennevogel commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +{% include partials/_series-of-posts-about-scm-integration.md %}
I wouldn't add this. It doesn't matter how we got here, it matters that we are here.

2022-09-20 15:10 UTC, saraycp commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +
Done, but I moved the images to _What Is This About?_ section. They make more sense there where we mention workflows and SCM reports.

2022-09-20 15:11 UTC, saraycp commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +{% include partials/_series-of-posts-about-scm-integration.md %}
I don't include the partial on this post then.

2022-09-21 09:20 UTC, saraycp commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +You can learn more about our journey by reading our previous blog posts about the SCM/CI integration feature.
No, I decided to leave it there to invite people to read more... But let me remove it and organize the paragraphs differently.

2022-09-21 09:25 UTC, saraycp commented on _posts/development/2022-09-21-trigger-workflow-rollout.md
> +You can learn more about our journey by reading our previous blog posts about the SCM/CI integration feature.
Ok, I removed that sentence and merge the section with the previous one. Let me know what you think, please.

2022-09-21 09:30 UTC, hennevogel approved these changes

2022-09-21 11:19 UTC, merged