Blog post for watchlist roll-out
openSUSE/obs-landing pull request #375
Opened 2022-09-21 13:35 UTC by rubhanazeem

2022-09-21 13:37 UTC, rubhanazeem commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rollout new_watchlist (M)](https://trello.com/c/MgdvMBCT/1980-rollout-newwatchlist-m)

2022-09-22 09:23 UTC, hennevogel commented
nice copy and paste job 😉

2022-09-22 09:31 UTC, saraycp requested changes
The text seems too similar to the previous blog post one. As we are going to publish them one after the other, I propose to change some sentences.

2022-09-22 09:31 UTC, saraycp commented on _posts/development/2022-09-26-watchlist-rollout.md
> +forward today, we are now ready to push it out of the beta program and make it available in OBS.
```suggestion
We enabled the new watchlist feature in February 2022 under the beta program. Since then, we have been improving this feature thanks to the valuable feedback coming from our users. Moving
forward today, we are now ready to push it out of the beta program and make it generally available in OBS.
```

2022-09-22 10:05 UTC, rubhanazeem commented
I've added the requested changes. @saraycp  @hennevogel should we mention anything about the migration?

2022-09-22 10:36 UTC, saraycp commented
> I've added the requested changes. @saraycp @hennevogel should we add something about the migration?

We should. Whatever the final decision is, we need to inform the users.

2022-09-26 09:48 UTC, hennevogel requested changes
There are also a couple of new notification settings. Notifications are basically 50% of this feature, you should mention them.

2022-09-26 09:48 UTC, hennevogel commented on _posts/development/2022-09-26-watchlist-rollout.md
> +### Advantages of the New Watchlist
```suggestion
## Watch projects, packages and requests!
```

2022-09-26 10:58 UTC, rubhanazeem commented
@hennevogel  I've mentioned notifications

2022-09-26 11:00 UTC, danidoni commented on _posts/development/2022-09-26-watchlist-rollout.md
> +There are many options available in notification settings. The new watchlist ables you to receive
```suggestion
There are many options available in notification settings. The new watchlist allows you to receive
```

2022-09-26 11:32 UTC, hennevogel approved these changes

2022-09-26 12:04 UTC, saraycp approved these changes

2022-09-26 12:49 UTC, merged