Blog post about Gitea integration
openSUSE/obs-landing pull request #376
Opened 2022-09-27 14:32 UTC by saraycp

2022-09-27 14:57 UTC, krauselukas commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +Around September 2022, the feature was quite stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the mileston
```suggestion
Around September 2022, the feature was stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the milestone of [supporting Gitea](2022/09/27/gitea_integration) on top of GitHub and GitLab._
```

2022-09-27 14:58 UTC, krauselukas commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +Around September 2022, the feature was quite stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the mileston
@saraycp IMO we can be more confident :)

2022-09-27 15:01 UTC, krauselukas commented on _posts/development/2022-09-28-gitea_integration.md
> +All you need to know is in our [user documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html). Enjoy setting up the integration with Gitea and
```suggestion
All you need to know is available in our [user documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html). Enjoy setting up the integration with Gitea and please let the feedback comming.
```

2022-09-27 15:02 UTC, krauselukas commented on _posts/development/2022-09-28-gitea_integration.md
> +All you need to know is in our [user documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html). Enjoy setting up the integration with Gitea and
```suggestion
All you need to know is in our [user documentation](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration.html). Enjoy setting up the integration with Gitea and please let the feedback coming.
```

2022-09-27 15:05 UTC, krauselukas commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +Around September 2022, the feature was quite stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the mileston
```suggestion
Around September 2022, the feature was considered stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the milestone of [supporting Gitea](2022/09/27/gitea_integration) on top of GitHub and GitLab._
```

2022-09-27 15:06 UTC, krauselukas commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +Around September 2022, the feature was quite stable, so we [enabled it for all the OBS users](2022/09/21/trigger-workflow-rollout), but that wasn't the end; later in September we reached the mileston
I like this term a bit more, but I'm also fine with your version

2022-09-27 15:08 UTC, hennevogel requested changes

2022-09-27 15:08 UTC, hennevogel commented on _posts/development/2022-09-28-gitea_integration.md
> +title: Gitea Joins the Party!
```suggestion
title: Gitea Joins the SCM/CI Party!
```

2022-09-27 15:08 UTC, hennevogel commented on _posts/development/2022-09-28-gitea_integration.md
> +We have discovered your need of setting up an integration between Gitea and OBS.
```suggestion
It was our idea from the beginning to make this SCM agnostic because there are so many of them we would like to support.
```

2022-09-27 15:45 UTC, saraycp commented on _posts/development/2022-09-28-gitea_integration.md
> +We have discovered your need of setting up an integration between Gitea and OBS.
I phrased it slightly different.

2022-09-27 15:58 UTC, hennevogel approved these changes

2022-09-27 16:27 UTC, saraycp commented
I pushed the image again, the previous one was blurry.

2022-09-28 10:34 UTC, krauselukas approved these changes

2022-09-28 10:50 UTC, saraycp commented
In my last two pushes I included the partial about the series of blog posts and I updated the image again, this time it was pixelated.

2022-09-28 11:16 UTC, merged