Blog post for sprint 128 - request redesign
openSUSE/obs-landing pull request #382
Opened 2022-10-24 10:11 UTC by rubhanazeem

2022-10-24 10:36 UTC, danidoni commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +There was no way to know the history and conversations happened in a superseded requests. The only possible way to check the history was to visit the superseded request page. Now we have improved it
```suggestion
There was no way to know the history and conversations happened in a superseded requests. The only possible way to check the history was to visit the superseded request page. Now we have improved it and the history from superseded requests is now available in the superseding requests.
```

2022-10-24 10:37 UTC, danidoni commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +Build results are one of the most important features for the OBS users. Now the request page presents build results in it's separate tab.
```suggestion
Build results are one of the most important features for the OBS users. Now the request page presents build results in a separate tab.
```

2022-10-24 11:03 UTC, hennevogel requested changes

2022-10-24 11:03 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +There was no way to know the history and conversations happened in a superseded requests. The only possible way to check the history was to visit the superseded request page. Now we have improved it
You are describing the change from first iteration to this now. I think what you should describe is the change from what was there before on the old request page to how it's done now.

2022-10-24 11:03 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +A very common usecase when working with requests is to pointout a change in diffs. For example if someone has removed or added something new in the code. Now it's very easy to point to that change by
This is actually a bug fixed throughout the app, not very specific to this opportunity. And for sure not more important than build results. I would mention it at the end, if at all...

2022-10-24 11:03 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +Build results are one of the most important features for the OBS users. Now the request page presents build results in a separate tab.
Why is it important? And why is it important in the Request context? You should spell that out.

2022-10-24 12:35 UTC, rubhanazeem commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +A very common usecase when working with requests is to pointout a change in diffs. For example if someone has removed or added something new in the code. Now it's very easy to point to that change by
Okay, I've removed it

2022-10-24 12:35 UTC, rubhanazeem commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +There was no way to know the history and conversations happened in a superseded requests. The only possible way to check the history was to visit the superseded request page. Now we have improved it
Its updated

2022-10-24 16:25 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +Build results are one of the most important features for the OBS users. They are specifically important for requests because they help you to verify if your changes are working or not. Now we present
```suggestion
Build results are specifically important for requests because they help you to verify if the submitted changes are working or not. Now we present build results in a separate tab on request page.
```

2022-10-24 16:25 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +  <img src="/images/posts/build-results.png" alt="A screenshot of the build results" />
Make sure you update the screenshot to the latest state.

2022-10-25 07:37 UTC, rubhanazeem commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +If you create a request superseding request, conversation and history of the superdeded request was not visible. The only possible way to check the history was to visit the superseded request page. N
Right, I was referring to the new view.

2022-10-25 07:37 UTC, rubhanazeem commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +  <img src="/images/posts/build-results.png" alt="A screenshot of the build results" />
It's updated

2022-10-25 10:36 UTC, hennevogel requested changes

2022-10-25 10:36 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +If you create a superseding request, conversation and history of the superdeded request was not visible. The only possible way to check the history was to visit the superseded request page. Now we ha
```suggestion
In the old design the conversation of a superseded request was presented in a tab. Because the conversation on the current request is very often "just" the continuation of people talking about the previous request. We brought this back and integrated the conversation right into the stream (collapsed by default).
```

2022-10-25 10:36 UTC, hennevogel commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +  <img src="/images/posts/build-results.png" alt="A screenshot of the build results" />
This is still not it. Guess you are looking at production, I don't think it's deployed yet.

2022-10-25 11:12 UTC, saraycp requested changes

2022-10-25 11:12 UTC, saraycp commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +We don't stop improving the requests workflow and we are actively working on the feedback. This time we worked on including conversations from superseded requests, and presenting build results.
```suggestion
We don't stop improving the requests workflow and we are actively working on the feedback. This time we worked on including conversations from superseded requests and presenting build results.
```

2022-10-25 11:12 UTC, saraycp commented on _posts/development/2022-10-24-request-workflow-redesign.md
> +In the old design the conversation of a superseded request was presented in a tab. Because the conversation on the current request is very often "just" the continuation of people talking about the pr
```suggestion
In the old design, the conversation of a superseded request was presented in a tab. Because the conversation on the current request is very often "just" the continuation of people talking about the previous request. We brought this back and integrated the conversation right into the stream (collapsed by default).
```

2022-10-25 11:12 UTC, saraycp commented on _includes/partials/_series-of-posts-about-request-redesign.md
> +_We started the [redesign of the request workflow](/2022/08/15/request-workflow-redesign) in August 2022. Then we focused on the [support of multi-action submit requests](/2022/09/14/request-workflow
We usually mention the blog post we are publishing as well. So I propose something like:

```suggestion
_We started the [redesign of the request workflow](/2022/08/15/request-workflow-redesign) in August 2022. Then, in September 2022, we focused on the [support of multi-action submit requests](/2022/09/14/request-workflow-redesign-round-two) to continue now with [improvements regarding the Build Results tab and superseded conversations](/2022/10/24/request-workflow-redesign)._
```

2022-10-25 13:43 UTC, saraycp approved these changes

2022-10-25 14:02 UTC, hennevogel approved these changes

2022-10-25 14:05 UTC, merged