Add post mortem for incident on the 6th February 2023
openSUSE/obs-landing pull request #396
Opened 2023-02-06 15:07 UTC by krauselukas

2023-02-06 15:30 UTC, hennevogel requested changes

2023-02-06 15:39 UTC, hennevogel commented on _posts/deployments/2023-02-06-post-mortem.md
> +A recently setup hidden project on our [reference server](https://build.opensuse.org) server.
something happened on Friday around 22:30 to `multimedia:libs:cisco-openh264`. What?

2023-02-08 12:06 UTC, krauselukas commented on _posts/deployments/2023-02-06-post-mortem.md
> +The problem was caused by failing mailer jobs, which started to block the delayed job queue. The mailer jobs were failing
I adapted the text, please have another look :)

2023-02-08 12:06 UTC, krauselukas commented on _posts/deployments/2023-02-06-post-mortem.md
> +A recently setup hidden project on our [reference server](https://build.opensuse.org) server.
I adapted the text, please have another look :)

2023-02-08 16:59 UTC, hennevogel requested changes

2023-02-08 16:59 UTC, hennevogel commented on _posts/deployments/2023-02-06-post-mortem.md
> +failing and blocked other mailer jobs.
Still not true. Nothing blocked other mailer jobs. There is just one mail job and it crashed :)

2023-02-08 16:59 UTC, hennevogel commented on _posts/deployments/2023-02-06-post-mortem.md
> +and processing of all other mailer jobs again.
```suggestion
and processing of mailer jobs again.
```

2023-02-08 16:59 UTC, hennevogel commented on _posts/deployments/2023-02-06-post-mortem.md
> +Fortunately there is only one project affected, that had to be excluded for now.
I don't think this is info the internet needs to know 😺

2023-02-08 21:27 UTC, krauselukas commented on _posts/deployments/2023-02-06-post-mortem.md
> +Fortunately there is only one project affected, that had to be excluded for now.
true, removed

2023-02-08 21:27 UTC, krauselukas commented on _posts/deployments/2023-02-06-post-mortem.md
> +## Timeline (CEST)
upps

2023-02-09 12:10 UTC, hennevogel approved these changes

2023-02-09 12:11 UTC, merged