Add blogpost for sprint 135 request page redesign
openSUSE/obs-landing pull request #401
Opened 2023-03-06 12:27 UTC by rubhanazeem

2023-03-06 12:57 UTC, krauselukas commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +It's been a while since we have been working on improving the request page redesign. This time we have focused on adding comments on changed or removed lines in a diff, support for add role requests,
@rubhanazeem I wouldn't say "its been a while". There was just one sprint in between :) or do you want to say that its been a while since the kick-off?

2023-03-06 12:57 UTC, krauselukas commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +title: Request Page Redesign - Diff comments, add role requests actions, and more
```suggestion
title: Request Page Redesign - Diff comments, request actions for user role additions, and more
```

2023-03-06 13:01 UTC, krauselukas commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +A review process is incomplete until it is possible to have a conversation about code changes. Sometimes a reviewer would like to know the reason for a specific change, or maybe the creator of the re
```suggestion
A review process is incomplete until it is possible to have a conversation about code changes. Sometimes a reviewer would like to know the reason for a specific change, or maybe the creator of the request would like to point out a line of code they have changed in their request. It is easy to lose track of conversation when the process is not seamlessly defined. That's why now it is possible to add comments on changed and removed lines.
```

2023-03-06 13:02 UTC, krauselukas commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +### Add Role Actions
```suggestion
### Add Request Actions for User Role Additions
```

2023-03-06 13:03 UTC, krauselukas commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +### Add Role Actions
@rubhanazeem I know in the codebase we often just talk about "roles", but I think we should be a bit more specific what those roles about

2023-03-06 13:42 UTC, hennevogel commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +A review process is incomplete until it is possible to have a conversation about code changes. Sometimes a reviewer would like to know the reason for a specific change, or maybe the creator of the re
> It is easy to lose track of conversation when the process is not seamlessly defined.

Not sure what you want to say here?

2023-03-06 15:46 UTC, saraycp requested changes

2023-03-06 15:46 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +It's been a while since we have been working on improving the request page redesign. This time we have focused on adding comments on changed or removed lines in a diff, support for add role requests,
"working on improving the request page redesign" sounds redundant to me, so I'd say either "working on improving the request page" or "working on the request page redesign".

But I also think we can simplify the sentence like follows:

```suggestion
For some time now we have been working on the request page redesign. This time we have focused on adding comments on changed or removed lines in a diff, supporting add role requests, and enhancing the requests with multiple actions.
```

2023-03-06 15:46 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +### Add Request Actions for User Role Additions
As it's not only about User but also Group, I would simplify this to 
```suggestion
### Add Request Actions for Role Additions
```

2023-03-06 15:46 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +A request in OBS can have many types. Until now, we have been focusing on requests with the submit actions. This time we have also focused on the user role addition actions. The role addition request
```suggestion
A request in OBS can have many types of actions. Until now, the redesign had focused on the submit actions only. This time we have also covered the role addition actions, which are used when a user or a group wants to be a Maintainer or Bugowner of a project or a package. The UI is adapted for the add role actions to provide action-specific information that can help the reviewers.
```

2023-03-07 11:46 UTC, saraycp requested changes

2023-03-07 11:46 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +title: Request Page Redesign - Diff Comments, Request Actions for User Role Additions, and More
We can do here what we did with the other title. We don't mention User/Group and the text is simplified a bit.

```suggestion
title: Request Page Redesign - Diff Comments, Request Actions for Role Additions, and More
```

2023-03-07 11:46 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +A review process is incomplete until it is possible to have a conversation about code changes. Sometimes a reviewer would like to know the reason for a specific change, or maybe the creator of the re
I'll split this long paragraph and will be more specific with the limitations:

```suggestion
A review process is incomplete until it is possible to have a conversation about code changes. Sometimes a reviewer would like to know the reason for a specific change, or the creator of the request would like to point out a line of code they have changed in their request. It is easy to lose track of conversation when the process is not seamlessly defined. That's why now it is possible to add comments on changed and removed lines.

Please bear in mind that this is only the first step. There are more updates yet to come like notifying the involved users when someone writes a comment on a diff or displaying that comment in the general conversation tab.
```

2023-03-07 14:11 UTC, saraycp requested changes

2023-03-07 14:11 UTC, saraycp commented on _posts/development/2023-03-06-request-workflow-redesign.md
> +</figure>
Please swap the order of the paragraph and image.

```suggestion
<figure>
  <img src="/images/posts/sprint-135-diff-comments.png" alt="A screenshot of diff comment" />
  <figcaption>Diff comment</figcaption>
</figure>

Please bear in mind that this is only the first step. There are more updates yet to come like notifying the involved users when someone writes a comment on a diff or displaying that comment in the general conversation tab.
```

2023-03-07 14:11 UTC, saraycp commented on _includes/partials/_series-of-posts-about-request-redesign.md
> +This time we have focused on [enhancing the review process with diff comments](/2023/03/06/request-workflow-redesign)._
Please change the date in the file name and here. It seems we are going to publish it today, so `2023-03-07` and `2023/03/07`.

2023-03-07 14:31 UTC, saraycp approved these changes

2023-03-07 14:50 UTC, merged