Blog post about API documentation rollout
openSUSE/obs-landing pull request #411
Opened 2023-05-31 17:03 UTC by saraycp

We must inform our users right before/after we roll out the new API documentation.

Here you are the blog post I propose. Please have a look so it's ready to use when needed.

TODO:

- [ ] Adapt the date in the file name and the partial.

2023-06-01 11:02 UTC, danidoni approved these changes

2023-06-01 11:03 UTC, danidoni commented
LGTM

2023-06-01 14:41 UTC, hennevogel requested changes

2023-06-01 15:21 UTC, eduardoj commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Our goal is to make the work easier for users and contributors. Please keep the feedback coming, it will help you and us.
@hennevogel, we need your help here, not only to say what is left, but to write something big as you expect.

Don't hesitate to write some paragraphs about all this journey you also have experienced in this blog post. That would be extremely welcomed.

2023-06-01 15:53 UTC, eduardoj commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Our goal is to make the work easier for users and contributors. Please keep the feedback coming, it will help you and us.
I want to inform our users right after we roll out the new API documentation.

We have more time: beginning next week.

2023-06-05 08:56 UTC, saraycp commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Our goal is to make the work easier for users and contributors. Please keep the feedback coming, it will help you and us.
@hennevogel I could propose something. Or did you write something already??

2023-06-05 12:11 UTC, eduardoj commented
I like it soooo much. Thanks a lot, Saray. :raised_hands: 

We could rename the file of the blog post and also the text which links to it (`_includes/partials/_series-of-posts-about-api-docs.md`) to the day of tomorrow: 2023-06-06.

2023-06-05 12:40 UTC, saraycp commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Enjoy the new docu! 📖 The URL stays the same: [https://build.opensuse.org/apidocs](https://build.opensuse.org/apidocs/index). Whereas the discontinued documentation has been moved to [https://build.o
So the "official" URL so far will no longer be the official one... 
It was `https://build.opensuse.org/apidocs` before but now it's `https://api.opensuse.org/apidocs/`.

2023-06-05 12:45 UTC, eduardoj commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Enjoy the new docu! 📖 The URL stays the same: [https://build.opensuse.org/apidocs](https://build.opensuse.org/apidocs/index). Whereas the discontinued documentation has been moved to [https://build.o
Exactly.

2023-06-05 12:48 UTC, saraycp commented on _posts/development/2023-06-02-api-docs-rollout.md
> +Enjoy the new docu! 📖 The URL stays the same: [https://build.opensuse.org/apidocs](https://build.opensuse.org/apidocs/index). Whereas the discontinued documentation has been moved to [https://build.o
I rephrased the whole paragraph.

2023-06-05 16:41 UTC, hennevogel requested changes
I think you are missing a bit more explanation of how to use this whole thing from the customer perspective. [swagger-ui](https://swagger.io/tools/swagger-ui/) is not super self-explanatory and neither is contributing to [OBS-v2.10.50.yaml](https://api.opensuse.org/apidocs-new/OBS-v2.10.50.yaml)

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- documentation that heavily relied on XML examples and schema files, two concepts that weren't clear enough for contributors;
We still heavily use both no?

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- a more standardized way to document the API, which might increase the number of contributions.
```suggestion
- a more standardized way to document the API, which hopefully increase the number of contributions.
```

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +title: The New API Documentation Is Rolled Out!
```suggestion
title: OpenAPI Specification for the Open Build Service HTTP API
```

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +One where any member of the OBS community can contribute to the OBS API documentation and use the OBS API easily and efficiently 👏
```suggestion
Your journey to get, use and contribute to the OBS API documentation! 👏
```

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +The team's journey to remake the API documentation has come to an end, but the most exciting journey is about to begin!
```suggestion
Our journey to remake the API documentation has come to an end, but the most exciting journey is about to begin.
```

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +title: The New API Documentation Is Rolled Out!
@eduardoj are we using a specific OpenAPI spec version?

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +With the rollout, we are moving away from:
Rollout is a concept not many of your customers will be aware of. I wouldn't mention it.

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +To summarize, we now provide a way to create and update the OBS API, easier to read for OBS newcomers and long-time users, and easier to document for OBS developers. What a great achievement!
I find self back-patting super cheesy... Let others say what kind of achievement this is. But that might just be me... :)

2023-06-05 16:41 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +Enjoy the new docu! 📖 The URL is [https://api.opensuse.org/apidocs/](https://api.opensuse.org/apidocs/). The discontinued documentation will be available in [https://build.opensuse.org/apidocs-old/](
Famous last words, I bet you this will be around for a very long time. Don't promise what you can't keep...

2023-06-05 17:20 UTC, saraycp commented
@hennevogel I address all your feedback. Only waiting for the answer to

> @eduardoj are we using a specific OpenAPI spec version?

to specify the version number if needed.

2023-06-05 17:35 UTC, eduardoj commented
> @hennevogel I address all your feedback. Only waiting for the answer to
> 
> > @eduardoj are we using a specific OpenAPI spec version?
> 
> to specify the version number if needed.

Yes, we are. It's defined here:

https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs-new/OBS-v2.10.50.yaml#L1

2023-06-06 07:45 UTC, saraycp commented
> I think you are missing a bit more explanation of how to use this whole thing from the customer perspective. [swagger-ui](https://swagger.io/tools/swagger-ui/) is not super self-explanatory and neither is contributing to [OBS-v2.10.50.yaml](https://api.opensuse.org/apidocs-new/OBS-v2.10.50.yaml)
> 
> Yet those are the two things you want people to do after reading this blog post right?

I'm with this now..

2023-06-06 11:20 UTC, saraycp commented
@eduardoj @hennevogel please have another look.

I added two sections talking about how to use the docu and how to contribute.

I finally mentioned the OpenAPI version in the content, not in the title:

> First of all, you need to understand what is Swagger UI and learn the OpenAPI 3.0.0 Specification.

2023-06-06 11:58 UTC, eduardoj commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- Declare the new endpoint in [OBS-v2.10.50.yaml](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs/OBS-v2.10.50.yaml). Please keep the alphabetical order.
A contribution to the documentation will not necessarily mean adding an endpoint. I would rephrase this as:
```suggestion
- If you are documenting a new endpoint, add it in [OBS-v2.10.50.yaml](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs/OBS-v2.10.50.yaml). Please keep the alphabetical order.
```

2023-06-06 12:02 UTC, eduardoj commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- Define the endpoint in YAML format under the [paths/](https://github.com/openSUSE/open-build-service/tree/master/src/api/public/apidocs/paths) directory.
Also here, contributions will not always mean to define new endpoints. I also find `in YAML format` kind of redundant. I would use something like:
```suggestion
- Define or modify how endpoints behave under the [paths/](https://github.com/openSUSE/open-build-service/tree/master/src/api/public/apidocs/paths) directory.
```

2023-06-06 12:04 UTC, danidoni commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- Declare the new endpoint in [OBS-v2.10.50.yaml](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs/OBS-v2.10.50.yaml). Please keep the alphabetical order.
I think the correct way is `add it to ...`

2023-06-06 12:19 UTC, hennevogel commented on _posts/development/2023-06-06-api-docs-rollout.md
> +- Declare the new endpoint in [OBS-v2.10.50.yaml](https://github.com/openSUSE/open-build-service/blob/master/src/api/public/apidocs/OBS-v2.10.50.yaml). Please keep the alphabetical order.
> Please keep the alphabetical order.

I think this is too much information.

2023-06-06 13:39 UTC, eduardoj requested changes
Thanks for the suggestions! Just a couple of minor changes I found we should need, in the "thank you" section.

2023-06-06 13:39 UTC, eduardoj commented on _posts/development/2023-06-06-api-docs-rollout.md
> +And a wholeheartedly thank you to everyone that has contributed and gave us feedback during the development of this.
```suggestion
And a wholeheartedly thank you to everyone that has created the initial API documentation, and later on, contributed and gave us feedback during the development of this new documentation.
```

I would also mention the people who created the initial documentation, which served us as base to create the new one.

Also, finishing the sentence with "... of this." sounded weird.

2023-06-06 14:51 UTC, eduardoj commented on _posts/development/2023-06-06-api-docs-rollout.md
> +And a wholeheartedly thank you to everyone that has contributed and gave us feedback during the development of this.
By "initial API documentation" I mean "now discontinued API documentation". I will modify this suggestion in another comment.

2023-06-06 14:57 UTC, eduardoj commented on _posts/development/2023-06-06-openapi-documentation.md
> +And a wholeheartedly thank you to everyone that has contributed and gave us feedback during the development of this new documentation.
```suggestion
A wholehearted thank you to everyone that created the now discontinued API documentation, and also to those who have contributed and given us feedback during the development of this new documentation.
```

2023-06-06 14:59 UTC, saraycp commented on _posts/development/2023-06-06-openapi-documentation.md
> +And a wholeheartedly thank you to everyone that has contributed and gave us feedback during the development of this new documentation.
It's clearer now. You meant "the former API" and not our first contributions to the new one. I misunderstood before, sorry. Adding the change...

2023-06-06 15:22 UTC, merged