Post-mortem June 20
openSUSE/obs-landing pull request #415
Opened 2023-06-20 15:12 UTC by rubhanazeem

2023-06-20 15:14 UTC, danidoni commented on _posts/deployments/2023-06-20-post-mortem.md
> +Do not perform admin/management tasks for data deleteion in production until you are sure because it inherent risks of using it incorrectly and breaking things.
```suggestion
Do not perform admin/management tasks for data deletion in production until you are sure because it inherent risks of using it incorrectly and breaking things.
```

2023-06-20 15:14 UTC, danidoni commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Once the issue was analyzed, we were able to fully fixed the issue in couple of minutes.
```suggestion
- Once the issue was analyzed, we were able to fully fix the issue in couple of minutes.
```

2023-06-20 15:45 UTC, hennevogel requested changes

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +title: "Post-mortem: deletion of an architecture (i586)"
```suggestion
title: "Post-mortem: Staging Workflow Unavailable"
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +In efforts to add new repository Debian 12, architecture i586 was deleted.
```suggestion
In our efforts to add a distribution (Debian 12), we accidentally deleted an entry in our architecture database table. That made all attempts to fetch this architecture through associations crash.
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +[Staging dashboard](https://build.opensuse.org/staging_workflows/openSUSE:Factory) for [openSUSE:Factory](https://build.opensuse.org/staging_workflows/openSUSE:Factory) was not accessible.
```suggestion
The [staging workflow for openSUSE:Factory](https://build.opensuse.org/staging_workflows/openSUSE:Factory) was not accessible for 34 minutes.
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +A distribution could have more than one architectures. We added a new repository for Debian 12 with two architectures .i.e., i586 and x86_64. But after reading release post from Debian we realise i58
That is not exactly what happened. We did not delete `Architecture` from all `Distribution`. We deleted the `Architecture` itself. It's used in a lot of places, the staging workflow for instance has nothing to do with `Distribution`.

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +OBS was not able to find i586 architecture for any repository.
```suggestion
Loading (through associations) the `Architecture` we deleted from the database.
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +We started receiving exceptions in Errbit error catcher.
```suggestion
Our [people on call](https://trello.com/c/IKZgDuaD) started to see exceptions pile up in our [exception tracker](https://errbit.opensuse.org/).
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +We created a new architecture entry for i586 in database.
```suggestion
We re-created the row in the `Architecture` table in our database.
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Discuss better solutions to perform such actions.
This is not an Action Item. Action items are tracked somewhere, like an issue or card. 

Also better solutions than what? You do not mention what we did anywhere...

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +Do not perform admin/management tasks for data deleteion in production until you are sure because it inherent risks of using it incorrectly and breaking things.
This is not a lesson learned. We knew this before. It just has gone wrong. What's the real lesson here? :)

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Once the issue was analyzed, we were able to fully fixed the issue in couple of minutes.
This is true for every issue right? Once you analyzed it it's quick to fix. I think what you are trying to say is more something for where we got lucky. See below...

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- We were able to find the id of deleted record in matter of seconds.
I think this is where we got lucky. If we would not have this in terminal history somewhere....

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- The errors detected on Errbit were not clear and we were not able to realise the issue at first glance.
Not sure what you want to say with this? What was not clear?

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +Information we needed to create new entry in database was readily available.
How was it readily available?

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- 20/06/2023 12:43 - Detected some errors on errbit and got informed that the Factory Dashboard returns 500 errors.
```suggestion
- 20/06/2023 12:43 - Our on call people detected some errors on errbit
- 20/06/2023 12:50 - Our on call people checked with customers and they confirmed the problem with the staging workflow
```

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- 20/06/2023 13:09 - Find the root cause.
How? Where? What took 20 minutes?

2023-06-20 15:45 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- 20/06/2023 13:17 - Implemented solution of the problem.
```suggestion
- 20/06/2023 13:16 - Re-created the Architecture in the database
- 20/06/2023 13:16 - Verified that the exceptions stopped
```

2023-06-21 08:06 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +- The errors detected on Errbit were not clear and we were not able to realise the issue at first glance.
Exceptions were clear but we didn't realize soon enough about the frequency of those exceptions.

2023-06-21 08:29 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Discuss better solutions to perform such actions.
I think action items don't apply here. There are follow-up tasks to address it or anything to track.

2023-06-21 08:29 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +Do not perform admin/management tasks for data deleteion in production until you are sure because it inherent risks of using it incorrectly and breaking things.
It's updated. Please have a look

2023-06-21 08:31 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +A distribution could have more than one architectures. We added a new repository for Debian 12 with two architectures .i.e., i586 and x86_64. But after reading release post from Debian we realise i58
True. I've addressed it

2023-06-21 08:38 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +- 20/06/2023 13:09 - Find the root cause.
It's updated as well. Please check

2023-06-21 08:49 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Discuss better solutions to perform such actions.
I don't think so no. Here are two action items I can think of:

- Developer documentation about the `Distribution` feature
  - what is it?
  - how to setup a distribution from an already existing project?
  - how to setup a distribution from scratch?

- Admin interface to:
  - create a `Distribution` from an existing project
  - create a `Distribution` from scratch

2023-06-21 10:51 UTC, hennevogel requested changes

2023-06-21 10:51 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- An admin interface to create a Distribution from an existing project, and create a Distribution from scratch.
We have a documentation and a code bug tracker you can create tickets in...

2023-06-21 10:51 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +A distribution could have more than one architectures. We added a new repository for Debian 12 with two architectures .i.e., i586 and x86_64. But after reading release post from Debian we realise i58
```suggestion
A distribution can have an association to more than one architecture. We added a distribution for Debian 12 with two architectures: i586 and x86_64. But after reading [the release post from Debian](https://www.debian.org/News/2023/20230610) more closely we realized, i586 processors are not supported anymore. Then we accidentally deleted the unsupported architecture from the database table instead of deleting the association.
```

2023-06-21 10:51 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- We relatively quickly noticed exceptions as this did not throw an alert.
```suggestion
- We relatively quickly noticed exceptions as this did not throw an alert.
- During the time the Architecture was deleted only customers using the staging workflow code path tried to fetch it. Other code-paths would have thrown exceptions too but nobody used them....
```

2023-06-21 10:51 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +A distribution could have more than one architectures. We added a new repository for Debian 12 with two architectures .i.e., i586 and x86_64. But after reading release post from Debian we realize i58
```suggestion
A `Distribution` can have an association to more than one `Architecture`. We added a new `Distribution` for Debian 12 with two architectures: i586 and x86_64. But after reading [the release post from Debian](https://www.debian.org/News/2023/20230610) more closely, we realized that i586 processors are not supported anymore. While removing the unsupported architecture, we accidentally deleted it from the architectures database table instead of deleting the association.
```

2023-06-21 11:03 UTC, hennevogel requested changes

2023-06-21 11:03 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- 20/06/2023 13:16 - Verified that the exceptions stopped.
```suggestion
- 20/06/2023 12:32 - We accidentally deleted the architecture
- 20/06/2023 12:43 - Our on call people detected exceptions piling up
- 20/06/2023 12:50 - Our on call people checked with customers and they confirmed a problem with the staging workflow
- 20/06/2023 12:52 - Our on call people started to alert the team
- 20/06/2023 13:03 - We discovered our mistake that caused this
- 20/06/2023 13:07 - Our on call people declared the incident according to our  [incident management protocol](https://github.com/openSUSE/open-build-service/wiki/Incident-Management-Protocol) 
- 20/06/2023 13:16 - Re-created the Architecture in the database.
- 20/06/2023 13:16 - Verified that the exceptions stopped.
- 20/06/2023 13:17 - Our on call people declared the incident resolved
```

2023-06-21 12:55 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Add Grafana alert for 500 internal server errors.
```suggestion
- Improve alerting for requests that result in internal server errors
```

2023-06-21 12:57 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- An admin interface to create a Distribution from an existing project, and create a Distribution from scratch.
So you are not going to create and link them? :)

2023-06-21 14:42 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- An admin interface to create a Distribution from an existing project, and create a Distribution from scratch.
A freestyle card or feature issue about creating an admin interface?

2023-06-22 07:46 UTC, rubhanazeem commented on _posts/deployments/2023-06-20-post-mortem.md
> +- An admin interface to create a Distribution from an existing project, and create a Distribution from scratch.
Done. I've created an issue in our freestyle and it is linked here. Same for the docu and I'll take care of writing developer docu.

2023-06-22 09:25 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Introduce incident management drills.
```suggestion
- [Introduce incident management drills](https://trello.com/c/GijvIK2Z).
```

2023-06-22 09:29 UTC, hennevogel commented on _posts/deployments/2023-06-20-post-mortem.md
> +- Improve [alerting](https://trello.com/c/MEGZQSLh/130-grafana-alerts-for-requests-that-result-in-internal-server-errors) for requests that result in internal server errors.
```suggestion
- Improve [alerting](https://trello.com/c/MEGZQSLh) for requests that result in internal server errors.
```

2023-06-22 12:15 UTC, merged