Introduce the new versioning options for the SCM/CI integration
openSUSE/obs-landing pull request #417
Opened 2023-06-26 21:17 UTC by danidoni

2023-06-28 07:51 UTC, eduardoj commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +title: Versioning in the SCM/CI Integration
```suggestion
title: Versioning arrives to SCM/CI Integration
```
Just another suggestion.

2023-06-28 08:39 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +title: Versioning in the SCM/CI Integration
I went for a variation on @hellcp-work's suggestion. WDYT?

2023-06-28 12:52 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +title: Versioning in the SCM/CI Integration
Sounds to me as if you are enabling larger changes in the SCM/CI workflow *right now*

2023-06-28 12:58 UTC, hennevogel requested changes

2023-06-28 12:58 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +Right now, we don't enforce a specific version in the yaml configuration. So if you don't set any version, your Workflow configuraiton will default to the latest minor version (1.1 as of the release
This sounds as if we are going to change this in the future. We wont...

2023-06-28 13:41 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +A minor version update will only include small, backwards-compatible changes. If you don't touch anything, your workflow will still work as before. Only when you make some minor adjustments to your w
Well, it's what we wrote [on the documentation](https://github.com/openSUSE/obs-docu/pull/292). I thought we already agreed on that.

2023-06-29 13:14 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +A minor version update will only include small, backwards-compatible changes. If you don't touch anything, your workflow will still work as before. Only when you make some minor adjustments to your w
Guess I missed that okay...

2023-06-29 13:23 UTC, hennevogel requested changes

2023-06-29 13:23 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +A major version update will introduce big features and may bring breaking changes, so it will require adapting your workflow configuration.
```suggestion
A major version update will introduce big features and may bring breaking changes, so it will require adapting your workflow configuration once you update to a new major version.
```

2023-06-29 13:23 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +Hello everyone!
nitpick: To me this greeting feels weird in a blog post...

2023-06-29 13:23 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +title: Enabling Larger Changes in SCM/CI Workflows
```suggestion
title: SCM/CI Workflow Versions. Making Larger Changes Less Painful For You.
```

2023-06-29 13:23 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
Hm and what version will it be if there are two minor versions? 1.1 and 2.1?

2023-06-29 13:27 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
1.1, because the we would be breaking everybody's config by switching to a major version

2023-06-29 13:30 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We are introducing the versioning as a way to release new features in the SCM/CI without breaking existing user's configuration. Those features are going to be released under a MAJOR.MINOR version sc
So better not giving that much detail?

2023-06-29 13:35 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +Hello everyone!
Okay, I'll remove it

2023-06-29 13:38 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We are introducing the versioning as a way to release new features in the SCM/CI without breaking existing user's configuration. Those features are going to be released under a MAJOR.MINOR version sc
Ah, the `probably`... okay, got it

2023-06-29 14:50 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
I guess you are tying to say: `least` or `lowest` minor version and not `latest`.

2023-06-30 08:41 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
I've been thinking about `least`, and I'm not sure: if we have `1.1` and `1.2`. I believe what @krauselukas thought when coming up with the versioning schema is to use the "biggest" of the "minor" version. I'm not sure if `least` is the word that translates to that then...

2023-06-30 10:54 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
[Pessimistic Version Constraint](https://guides.rubygems.org/patterns/#pessimistic-version-constraint) is what I was talking about

2023-06-30 11:52 UTC, hennevogel commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
We are making up a lot of stuff on the fly. I would not mention this to customers yet...

2023-06-30 11:58 UTC, danidoni commented on _posts/development/2023-06-23-new-versioning-options-for-the-scm-ci-integration.md
> +We won't enforce any specific version in the yaml configuration. So if you don't set any version, your Workflow configuration will default to the latest minor version (1.1 as of the release of this b
Then I will mention that we don't enforce any specific version on the workflow configuration, that we'll default to the lowest minor version and that's it

2023-06-30 12:06 UTC, hennevogel approved these changes

2023-06-30 12:13 UTC, danidoni commented on _posts/development/2023-06-30-new-versioning-options-for-the-scm-ci-integration.md
> +        event: **merge_request**
Yeah, it's true. Removing

2023-06-30 12:23 UTC, merged