Create post mortem post for 03.08.23
openSUSE/obs-landing pull request #420
Opened 2023-08-03 15:53 UTC by hellcp-work

2023-08-04 05:59 UTC, danidoni approved these changes

2023-08-04 07:51 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Impact**: Broken indexes on `project_log_entries`, `binary_releases`, `bs_request_actions` and `tokens` tables
```suggestion
**Impact**: Broken indexes on `project_log_entries`, `binary_releases`, `bs_request_actions` and `tokens` tables.
```

2023-08-04 07:51 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Root Causes**: Database cluster VM run out of available space. Generation of table indexes did not work
```suggestion
**Root Causes**: Database cluster VM run out of available space. Generation of table indexes did not work.
```

2023-08-04 07:52 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Root Causes**: Database cluster VM run out of available space. Generation of table indexes did not work
Also, generation as in creation?

2023-08-04 07:53 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Trigger**: Morning deployment and migration from utf8mb3 to utf8mb4
```suggestion
**Trigger**: Morning deployment and migration from utf8mb3 to utf8mb4.
```

2023-08-04 07:53 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Resolution**: The tables were dumped and restored from scratch
```suggestion
**Resolution**: The tables were dumped and restored from scratch.
```

2023-08-04 07:53 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Detection**: We were informed by BuildOPS who got notified via their monitoring
```suggestion
**Detection**: We were informed by BuildOPS who got notified via their monitoring.
```

2023-08-04 08:05 UTC, danidoni commented on _posts/deployments/2023-08-03-post-mortem.md
> +Only four tables ended up being affected
```suggestion
The rest of the migration except for those tables.

**What went wrong?**

* The current way we deploy with migration does not log the progress of migrations or inform us about things happening in real time.
* We don't know about errors coming from the database if there are any unless somebody tells us.
* We did not communicate this migration with the BuildOPS in advance to warn them of any potential fallout.

**Where we got lucky?**

Only four tables ended up being affected.
```

2023-08-04 10:00 UTC, hennevogel requested changes
you are missing [front matter](https://jekyllrb.com/docs/front-matter/)

2023-08-04 13:28 UTC, hennevogel requested changes

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Impact**: Broken indexes on `project_log_entries`, `binary_releases`, `bs_request_actions` and `tokens` tables.
Impact for customers not for the involved software.

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +On 3. August, a few hours after a large migration performed within the maintenance window earlier that day, we got notified about database errors coming from some of the tables.
We usually tell people how it affected them so they can identify what we are talking about. Remember we write this for everyone else, not for us.

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +The rest of the migration except for those tables.
Not sure what you want to say? That the change we made was good?

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Detection**: We were informed by BuildOPS who got notified via their monitoring.
```suggestion
**Detection**: Our database admins got notified via their monitoring.
```

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +**Root Causes**: Database cluster VM run out of available space. Generation of table indexes did not work.
```suggestion
**Root Causes**: Our database cluster ran out of available space during a large schema/data migration ([#14597 - Migrate the remaining database tables and columns to utf8mb4](https://github.com/openSUSE/open-build-service/pull/14597))
```

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* The current way we deploy with migration does not log the progress of migrations or inform us about things happening in real time.
Where is the action item to change this?

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* We don't know about errors coming from the database if there are any unless somebody tells us.
Not sure what you want to say with this. Can you explain?

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* We did not communicate this migration with the BuildOPS in advance to warn them of any potential fallout.
```suggestion
* We did not communicate this migration with our database admins in advance to make them aware of potential fallout.
```

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* There were people around who helped us in getting the database back to usable state.
```suggestion
* Our database admins where around to help us in getting the database back to usable state.
```

2023-08-04 13:28 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +- *13:37* Database cluster crashes
Hm, how did we survive this gap between 9 and 1?

2023-08-07 15:56 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +The rest of the migration except for those tables.
Yeah but which table was affected or not had little to do with the migration right? It's a bits misleading, as if the migration would be the cause...

2023-08-07 15:57 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* We don't know about errors coming from the database if there are any unless somebody tells us.
Well, no wonder right? We don't maintain the database cluster :)

2023-08-08 11:42 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +The rest of the migration except for those tables.
I wouldn't mention it at all. It has nothing really to do with the incident...

2023-08-08 11:44 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* The current way we deploy with migration does not log the progress of migrations or inform us about things happening in real time.
SRE I would say https://trello.com/b/Qx7osByV

2023-08-08 11:45 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* We don't know about errors coming from the database if there are any unless somebody tells us.
For sure not but you are capable of rewording :)

2023-08-08 14:54 UTC, hennevogel requested changes

2023-08-08 14:54 UTC, hennevogel commented on _posts/deployments/2023-08-03-post-mortem.md
> +* The current way we deploy with migration does not log the progress of migrations or inform us about things happening in real time.
```suggestion
* The current way we deploy with migration does not log the progress of migrations or inform us about things happening in real time ([improvement card](https://trello.com/c/iQKJUUaS)).
```

2023-08-08 15:29 UTC, hennevogel approved these changes

2023-08-08 15:29 UTC, merged