Add blog post for sprint 148 request page redesign
openSUSE/obs-landing pull request #427
Opened 2023-09-05 14:54 UTC by eduardoj

# Request build results overview:

### Simplified
![image](https://github.com/openSUSE/obs-landing/assets/7080830/37a64c74-f664-4b21-9847-35b1cdc4b144)

### Chart
![image](https://github.com/openSUSE/obs-landing/assets/7080830/5470645a-85d7-4895-a042-c8da5dd51e76)

2023-09-06 15:29 UTC, saraycp requested changes

2023-09-06 15:29 UTC, saraycp commented on _posts/development/2023-09-07-request-workflow-redesign.md
> +Last days, we have been working again on the request workflow redesign.
```suggestion
Lately, we have been working again on the request workflow redesign.
```

2023-09-06 15:29 UTC, saraycp commented on _posts/development/2023-09-07-request-workflow-redesign.md
> +We introduce the build results summary of a request and add a light improvement to the information returned of its mentioned issues.
```suggestion
We have introduced the build results summary of a request and improved the information displayed in the Mentioned Issues section.
```

2023-09-06 15:29 UTC, saraycp commented on _posts/development/2023-09-07-request-workflow-redesign.md
> +Apart from the detailed view of build results of a request in its own tab, you now also become a summary of the Build Results in the very first Conversation tab.
```suggestion
You still can see the detailed view in the Build Results tab but, from now on, you can also see a summary of the build results in the very first Conversation tab.
```

2023-09-06 16:17 UTC, eduardoj commented
@saraycp, I applied all your suggestions. Thanks!

2023-09-07 10:40 UTC, saraycp approved these changes
LGTM but I'd like someone involved in the deliverable to have a look. I could have missed some "semantic deficiencies" ...

2023-09-08 09:19 UTC, danidoni commented
Good job with the post! I like it!

2023-09-08 10:59 UTC, hennevogel requested changes

2023-09-08 10:59 UTC, hennevogel commented on _posts/development/2023-09-08-request-workflow-redesign.md
> +That is why we have opted for a more flexible approach.
I think it would be more clear what you are trying to convey if you, instead of describing a "summary" as a general idea, you explain the situation with multi action requests. Something like

> A submit request on OBS can be about one package that builds for one repository and one architecture like [boo#1104001](https://build.opensuse.org/request/show/1104001). Or it can be about 142 packages that build for many repositories that have multiple architectures, like [boo#1109684](https://build.opensuse.org/request/show/1109684). Showing what it relevant at a glance is easy for the former and more complicated for the latter....

2023-09-08 11:03 UTC, hennevogel commented on _posts/development/2023-09-08-request-workflow-redesign.md
> +</figure>
I think you need to explain that we are already have in our plan a page where you can leave the "summary" and go into details about this. https://trello.com/c/BQcRlesw

2023-09-08 12:16 UTC, eduardoj commented on _posts/development/2023-09-08-request-workflow-redesign.md
> +</figure>
I added a paragraph. Please take a look again.

2023-09-08 12:56 UTC, hennevogel approved these changes

2023-09-08 13:59 UTC, merged