Add post-mortem september 2023
openSUSE/obs-landing pull request #429
Opened 2023-09-19 15:17 UTC by saraycp

2023-09-19 15:38 UTC, hennevogel commented on _posts/deployments/2023-09-19-post-mortem.md
> +The error messages had to do with `moderated_at` and `code_of_conduct` database columns that the deployment tried to introduce.
None of your readers have the possibility to see that...

2023-09-19 16:12 UTC, danidoni commented on _posts/deployments/2023-09-19-post-mortem.md
> +* Another team member assumed the communicator role quickly.
I think this point may be important for us, but not for the people outside the team. I would drop it.

2023-09-20 09:24 UTC, hennevogel requested changes

2023-09-20 09:24 UTC, hennevogel commented on _posts/deployments/2023-09-19-post-mortem.md
> +* We weren't able to foresee that the migration could take longer than expected.
```suggestion
* We did not test how long the migration runs.
```

2023-09-20 10:55 UTC, saraycp commented on _posts/deployments/2023-09-19-post-mortem.md
> +After the morning deployment, many of the OBS pages were inaccessible returning a 500 error for less than 13 minutes.
Not only, on the same timeframe we also got [these erros](https://errbit.opensuse.org/apps/5620ca2bdc71fa00b1000000/problems/65095b8e84bf460703acd7be) about the `code_of_conduct` column.

2023-09-20 11:13 UTC, saraycp commented on _posts/deployments/2023-09-19-post-mortem.md
> +After the morning deployment, many of the OBS pages were inaccessible returning a 500 error for less than 13 minutes.
Well, the errors with `conde_of_conduct` happened in less than one minute, not so relevant... 
`First Notice: Sep 19 08:27:58 Last Notice: Sep 19 08:28:31`

2023-09-20 12:24 UTC, saraycp commented
@hennevogel I already push all the changes you suggested. Despite the fact

2023-09-21 09:52 UTC, danidoni approved these changes

2023-09-21 10:52 UTC, eduardoj approved these changes

2023-09-27 07:14 UTC, ncounter commented
@saraycp what is the state of this PR?

2023-10-04 08:57 UTC, saraycp commented
> @saraycp what is the state of this PR?

The blog post missed the Action Items section. I needed time to do some research and testing in order to provide possible solutions. As it is not straightforward, I've decided to add a generic text and go on working on it after this post-mortem is published:

_"Plan a strategy to deploy migrations. It might include separating migration deployment from the code changes deployment or splitting the migration into different steps"_

2023-10-05 08:07 UTC, bmwiedemann commented
> "Plan a strategy to deploy migrations. It might include separating migration deployment from the code changes deployment or splitting the migration into different steps"

That is a sensible approach. First we do the required changes to the database, ensure everything keeps working as before and in a 2nd deployment we add code to use the new DB parts. Would that split happen on the git level, where the PR to use the new parts would wait longer for merge?

2023-10-05 08:49 UTC, saraycp commented
> > "Plan a strategy to deploy migrations. It might include separating migration deployment from the code changes deployment or splitting the migration into different steps"
> 
> That is a sensible approach. First we do the required changes to the database, ensure everything keeps working as before and in a 2nd deployment we add code to use the new DB parts. Would that split happen on the git level, where the PR to use the new parts would wait longer for merge?

The order _migration deployment_ + _changes deployment_ works for the addition of columns/tables.
For removals, the order should be  _changes deployment_ + _migration deployment_, as we need the code to stop using those columns/tables before we remove them.

So far, we have relied on labels like "Reference Server" or "Do Not Merge" to avoid merging and deploying PRs that require special attention. We can use them for the cases we mentioned before until we find a better way to do that.

2023-10-10 09:44 UTC, hennevogel approved these changes

2023-10-10 09:53 UTC, dmarcoux commented on _posts/deployments/2023-10-09-post-mortem.md
> +On September 19th the pages and API routes on OBS displaying comments where inaccessible (returning a 500 error) to all users for 13 minutes. Here is what caused the problem.
```suggestion
On September 19th the pages and API routes on OBS displaying comments were inaccessible (returning a 500 error) to all users for 13 minutes. Here is what caused the problem.
```

2023-10-10 12:08 UTC, merged