Blogpost about comment locking and report categories
openSUSE/obs-landing pull request #431
Opened 2023-10-18 16:16 UTC by krauselukas

2023-10-18 16:32 UTC, eduardoj commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +that is better suited for this purpose. Until now the only option you had is to leave
```suggestion
that is better suited for this purpose. Until now, the only option you had is to leave
```

2023-10-18 16:33 UTC, eduardoj commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +a friendly comment with a hint. From now on you can simply lock the commenting
```suggestion
a friendly comment with a hint. From now on, you can simply lock the commenting
```

2023-10-18 16:33 UTC, eduardoj commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +will be able to leave a comment, for everyone else it will be locked.
```suggestion
will be able to leave a comment. For everyone else it will be locked.
```

2023-10-18 16:35 UTC, eduardoj commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +a forbidden license. To avoid that you have to repeat yourself, we introduced
```suggestion
a forbidden license, ... To avoid that you have to repeat yourself, we introduced
```

2023-10-18 16:38 UTC, eduardoj requested changes
I left a couple of suggestions, mostly related to punctuation.

I also suggest you write every sentence in a different line: it would make no difference when rendering the page, but it will make easier to review the text.

2023-10-18 19:18 UTC, saraycp commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +All of the following is part of the *Content Moderation* [beta program](/2018/10/04/the-beta-program/).
This is the second blog post regarding Moderation. I'd say it's time to _include_ the paragraph mentioning all the blog posts related to the topic. As we do for other opportunities.

2023-10-18 19:22 UTC, saraycp commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +  <figcaption>Locked comment section from maintainer perspective</figcaption>
It's important people know that what they see in the image is only for maintainers. It's true that's clarified in the `figcaption` but it can go unnoticed. What about adding it as normal text right before the image?

2023-10-19 08:50 UTC, krauselukas commented on _posts/development/2023-10-18-comment-locking-and-report-categories.md
> +All of the following is part of the *Content Moderation* [beta program](/2018/10/04/the-beta-program/).
true, will do so

2023-10-19 13:46 UTC, krauselukas commented
@eduardoj @saraycp @hellcp-work please have another look, I addressed your reviews

2023-10-19 13:54 UTC, eduardoj commented
> @eduardoj @saraycp @hellcp-work please have another look, I addressed your reviews

I still miss this suggestion: "I also suggest you write every sentence in a different line: it would make no difference when rendering the page, but it will make easier to review the text."

2023-10-19 14:57 UTC, krauselukas commented
> > @eduardoj @saraycp @hellcp-work please have another look, I addressed your reviews
> 
> I still miss this suggestion: "I also suggest you write every sentence in a different line: it would make no difference when rendering the page, but it will make easier to review the text."

@eduardoj I overlooked it, its now applied

2023-10-20 09:27 UTC, krauselukas commented
@saraycp done :)

2023-10-20 13:05 UTC, eduardoj approved these changes

2023-10-20 13:05 UTC, saraycp approved these changes

2023-10-20 13:11 UTC, merged