Blogpost about sprint 152
openSUSE/obs-landing pull request #432
Opened 2023-10-30 15:38 UTC by rubhanazeem

2023-10-30 18:17 UTC, saraycp requested changes
I left a few comments but I'd also propose replacing all the `WorkflowRun` with `workflow run` in all their forms (singular, plural, title, etc)

2023-10-30 18:17 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +Whenever SCM/CI workflow executes you get a new entry of WorkflowRuns that gives all the details about status, event type, event source etc. But now OBS has the option to send notification if the Wor
```suggestion
Whenever an SCM/CI workflow is executed, you get a new entry of workflow run that gives all the details about status, event type, event source etc. But now OBS also gives you the possibility of receiving a notification as soon as one workflow run fails.

Give it a try! Subscribe to the new type of (notifications)[https://build.opensuse.org/my/subscriptions] so you don't have to manually check what's going on with your workflows. OBS will let you know as soon as something wrong happens.
```

2023-10-30 18:17 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +  <img src="/images/posts/workflow-run-notification-1.png" alt="Screenshot of workflow run notification activation" />
This is not the correct image to display here. Email should be enabled as well, we introduced it in a later PR.

2023-10-30 18:17 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +## Notifications about failed SCM/CI workflows
Titleized:

```suggestion
## Notifications About Failed SCM/CI Workflows
```

2023-10-30 18:17 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +## Workflow configuration file and SetFlag step artifacts in workflowRun
```suggestion
## Workflow Configuration File and SetFlag Step Artifacts in Workflow Run
```

2023-10-30 18:17 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +Previously, WorkflowRun only showed the path of workflow configuration file and now you can check the whole content of your workflow configuration file in WorkflowRun.
```suggestion
Previously, the workflow run details only included the URL or path to the workflow configuration file. Now it also includes the file content so you can always check what was the configuration at the time the workflow ran.
```

2023-10-31 10:28 UTC, rubhanazeem commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +A lot of stuff happens behind the scenes whenever OBS runs SCM/CI workflow. Sometimes, it gets hard to keep track of things like which workflow failed or completed successfully. So, this time we trie
I've addressed this. Please check

2023-10-31 10:29 UTC, rubhanazeem commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +  <img src="/images/posts/workflow-run-notification-1.png" alt="Screenshot of workflow run notification activation" />
The image has been updated

2023-10-31 11:03 UTC, saraycp requested changes

2023-10-31 11:03 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +In addition to the configuration file WorkflowRun now also stores the artifacts of SetFlag step.
```suggestion
In addition to the configuration file the workflow run now also stores the artifacts of the SetFlag step.
```

2023-10-31 11:05 UTC, saraycp requested changes

2023-10-31 11:05 UTC, saraycp commented on _posts/development/2023-10-30-notifications-failed-workflow-runs.md
> +A lot of things happen behind the scenes whenever OBS runs an SCM/CI workflow. Sometimes, you might want to know which workflow failed or completed successfully and the only way to do this is visitin
```suggestion
A lot of things happen behind the scenes whenever OBS runs an SCM/CI workflow. Sometimes, you might want to know which workflow failed or completed successfully and the only way to do this is by visiting the workflow runs UI. This time we tried to improve this and other details in the SCM/CI integration.
```

2023-10-31 11:55 UTC, saraycp approved these changes

2023-10-31 13:47 UTC, merged