Blogpost for sprint 163
openSUSE/obs-landing pull request #459
Opened 2024-04-17 08:29 UTC by ncounter

2024-04-17 15:19 UTC, krauselukas commented on _includes/partials/_series-of-posts-about-scm-integration.md
> +In December 2022 we introduced [placeholder variables in addition to a customizable configuration file location](/2022/12/20/scm-integration-workflows-file). Later on now we brought [notifications fo
```suggestion
In December 2022 we introduced [placeholder variables in addition to a customizable configuration file location](/2022/12/20/scm-integration-workflows-file). Later on we brought [notifications for failed workflow runs](/2023/10/30/notifications-failed-workflow-runs), and now we introduced a new way of listing the events by [multiple filter parameters](/2024/04/17/scm-multiple-filters)_
```

2024-04-17 15:28 UTC, hennevogel requested changes

2024-04-17 15:28 UTC, hennevogel commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +It is now possible to fine-grain filters listing WorkflowRun Events now by the multiple properties an event is defined by.
```suggestion
It is now possible to use more fine-grained filters for listing your SCM/CI Workflows runs. You can filter by event status, type, action and source and combine them any way you want.
```

2024-04-17 15:28 UTC, hennevogel commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +While branching a package by the SCM/CI integration, it is now provided the link to the target project that was not available before.
```suggestion
If your SCM/CI Workflow is branching a package, the project the package is branched to, now contains a link back the the PR/commit that caused this workflow to run.
```

2024-04-17 15:29 UTC, krauselukas commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +There is a new way to search for a Token's WorkflowRun Event.
@ncounter I wouldn't call it `Token's WorkflowRun Event`. I would just talk about `WorkflowRuns`

2024-04-17 15:39 UTC, hennevogel commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +There is a new way to search for a Token's WorkflowRun Event.
```suggestion
Every time your source code management system (github, gitlab etc.) sends a webhook to OBS to trigger a SCM/CI Workflow, we give our best to record what is happening during (and in case of builds even after) your workflow's steps run. We do this because this is a complicated feature, involving two very large applications, where lot's of things can go wrong. So you need loads of information to debug once something is.

We do this by recording things in a "log file" called workflow run. You can access them from the [/my/tokens](https://build.opensuse.org/my/tokens). We have just published a new search/filter interface for workflow runs.
```

2024-04-17 15:57 UTC, krauselukas commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +### Link the Target Project on Branching a package
```suggestion
### Provide a Link to the SCM Repository When Branching a Package
```

2024-04-17 16:02 UTC, krauselukas commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +While branching a package by the SCM/CI integration, it is now provided the link to the target project that was not available before.
```suggestion
When branching a package through the SCM/CI integration, we now include the link to the SCM repository in the target project description. 
```

2024-04-17 21:18 UTC, ncounter commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +There is a new way to search for a Token's WorkflowRun Event.
That was the root reason why I came up with a so poor wording: I felt it was self explanatory so I barely knew what to say differently. Then a [nice suggestion by Henne](https://github.com/openSUSE/obs-landing/pull/459#pullrequestreview-2006406607) came up and I very much like it, so I'd go for it if you agree too.

2024-04-17 21:22 UTC, ncounter commented
@hennevogel @krauselukas thank you for the review and the comments. I addressed them all by picking from you both the suggestions. Please give a second round of review.

2024-04-18 09:12 UTC, eduardoj commented on _posts/development/2024-04-17-scm-multiple-filters.md
> +  <img src="/images/posts/2024-04-17/workflowrun-multiple-filters.png" alt="Screenshot of workflow run multiple filters" />
```suggestion
  <img src="/images/posts/2024-04-18/workflowrun-multiple-filters.png" alt="Screenshot of workflow run multiple filters" />
```
Should we also change the date of the post? Also renaming this post file....

2024-04-18 10:41 UTC, hennevogel approved these changes

2024-04-18 12:07 UTC, merged