Add blog post about improved filters for notifications
openSUSE/obs-landing pull request #462
Opened 2024-06-11 10:28 UTC by eduardoj

2024-06-11 11:03 UTC, saraycp requested changes

2024-06-11 11:10 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Among the improvements on performance, you can now:
Applied. Thanks!

2024-06-11 11:11 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +![](/images/posts/2024-06-12/notifications-filters.gif)
True. I'll create another Gif including that part.

2024-06-11 11:44 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +![](/images/posts/2024-06-12/notifications-filters.gif)
Done. Please take a look again.

2024-06-11 13:53 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +We have prepared more improvements on how you get notified by OBS.
I would use one of those lines, but not both.

2024-06-11 13:55 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +If you want to be informed about what happens in your OBS instance, you most likely deal with lots of notifications.
I think this is not about what happens in the instance. Most users don't care about the instance, but the projects, packages and such things they work on. The notifications are for the user to stay on top of their work.

2024-06-11 13:56 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +- perform a "click and submit" on any option
I would rephrase this as something in the line of "less clicking" the details are not important

2024-06-11 13:58 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +We have prepared more improvements on how you get notified by OBS.
Yes, done.

2024-06-11 14:05 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +If you want to be informed about what happens in your OBS instance, you most likely deal with lots of notifications.
I rephrased the sentence. Please take a look.

2024-06-11 14:05 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +- perform a "click and submit" on any option
I also reprhrase this one.

2024-06-11 14:14 UTC, saraycp requested changes

2024-06-11 14:14 UTC, saraycp commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +- click and expect new results, meaning that your clicks wil be reduced
@suggestion
```
- click and expect new results, meaning that your clicks will be reduced
```

But I'd suggest something like `get results as soon as you click on any filter` @danidoni what do you think?

2024-06-11 14:17 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +- click and expect new results, meaning that your clicks wil be reduced
I like it. Changed.

2024-06-11 14:18 UTC, hennevogel commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Notifications are back, and they come with the strength of a pretty and revamped filtering page.
> Notifications are back

Where have they been? :)

2024-06-11 14:19 UTC, hennevogel commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Let's get into the details, and keep reading.
Might be some cultural thing but if some blog post tells me to keep reading I find that pretty arrogant...

2024-06-11 14:19 UTC, hennevogel commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Let's get into the details, and keep reading.
Might be some cultural thing but if some blog post tells me to keep reading I find that pretty arrogant...

2024-06-11 14:22 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Notifications are back, and they come with the strength of a pretty and revamped filtering page.
I see. I changed the sentence.

2024-06-11 14:22 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Let's get into the details, and keep reading.
I changed that sentence too. Please take a look again.

2024-06-11 14:24 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +If you want to be informed about what happens in your OBS instance, you most likely deal with lots of notifications.
Better!

2024-06-11 14:24 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +- perform a "click and submit" on any option
Perfect

2024-06-11 14:26 UTC, danidoni commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Let's get into the details and enjoy the reading!
```suggestion
Let's get into the details!
```
What about that?

2024-06-11 14:27 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Let's get into the details and enjoy the reading!
I like it too. :+1:

2024-06-11 15:04 UTC, saraycp requested changes

2024-06-11 15:04 UTC, saraycp commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Now, we are glad to present a set of changes, including a pretty and revamped filtering page.
```suggestion
Now, we are glad to present a set of changes, including a revamped filtering section.
```

Sorry, I didn't realize before. We don't have a "filtering page", that's why I suggest "filtering section".
And if it's "pretty" or not depends on users taste. It's something we shouldn't say.

2024-06-11 15:07 UTC, eduardoj commented on _posts/development/2024-06-12-notifications-improved-filtering.md
> +Now, we are glad to present a set of changes, including a pretty and revamped filtering page.
Applied. Thanks.

2024-06-11 15:10 UTC, saraycp approved these changes

2024-06-12 07:35 UTC, danidoni approved these changes

2024-06-12 09:45 UTC, merged