_redirects: add redirects for massive SEO link re-write
openSUSE/obs-landing pull request #466
Opened 2024-07-21 13:48 UTC by smithfarm

Otherwise we break an unknown number of external hyperlinks.

Refers-to: https://github.com/openSUSE/obs-docu/pull/364

2024-07-22 10:43 UTC, hennevogel requested changes

2024-07-22 10:43 UTC, hennevogel commented on _redirects
> +/help/manuals/obs-admin-guide/_backup /help/manuals/obs-admin-guide/backup
This looks wrong. The current PATH is `/help/manuals/obs-admin-guide/obs.cha.administration#_backup`

2024-07-22 17:04 UTC, smithfarm commented on _redirects
> +/help/manuals/obs-admin-guide/_backup /help/manuals/obs-admin-guide/backup
You're right. Hopefully fixed now.

2024-07-23 09:20 UTC, smithfarm commented
Aligned with the latest state of https://github.com/openSUSE/obs-docu/pull/364

2024-07-23 12:12 UTC, hennevogel approved these changes

2024-07-23 12:12 UTC, merged