Add blogpost about new request index feature
openSUSE/obs-landing pull request #469
Opened 2024-08-01 16:08 UTC by krauselukas

2024-08-02 12:26 UTC, danidoni approved these changes

2024-08-02 13:15 UTC, saraycp requested changes

2024-08-02 13:15 UTC, saraycp commented on _posts/development/2024-08-01-introduction-request-index.md
> +All those filters can be combined to fine grain the resulting list of requests.
```suggestion
All those filters can be combined to fine-grain the resulting list of requests.
```

2024-08-05 15:43 UTC, krauselukas commented on _posts/development/2024-08-05-introduction-request-index.md
> +The `Request Index` feature is part of the [beta program](/2018/10/04/the-beta-program/) and the requests list can be found under `Requests` on the left-hand side menu.
@saraycp I applied you suggestions 1:1. the only adaption i did was to add the part about "the left-hand side menu"

2024-08-05 16:16 UTC, eduardoj commented on _posts/development/2024-08-05-introduction-request-index.md
> +Right now we support simply listing all the requests, as well as filtering them by your incoming and outgoing ones.
```suggestion
Right now we support listing all the requests, as well as filtering them by your incoming and outgoing ones.
```
I could say that we already support more than we initially planned... but let's not minimize what we have all achieved.

2024-08-05 16:17 UTC, eduardoj requested changes

2024-08-05 16:17 UTC, eduardoj commented on _posts/development/2024-08-05-introduction-request-index.md
> +---
Don't forget to change the date of the file...

2024-08-06 09:27 UTC, saraycp commented on _posts/development/2024-08-05-introduction-request-index.md
> +The `Request Index` feature is part of the [beta program](/2018/10/04/the-beta-program/) and the requests list can be found under `Requests` on the left-hand side menu.
I didn't want to say left-hand side because the menu is at the bottom in smaller viewports.

What about...

```suggestion
The `Request Index` feature is part of the [beta program](/2018/10/04/the-beta-program/) and the requests list can be found under `Requests` on the _Places_ menu.
```

or something similar?

2024-08-06 12:36 UTC, krauselukas commented on _posts/development/2024-08-05-introduction-request-index.md
> +Right now we support simply listing all the requests, as well as filtering them by your incoming and outgoing ones.
applied

2024-08-06 12:36 UTC, krauselukas commented on _posts/development/2024-08-05-introduction-request-index.md
> +---
done

2024-08-06 12:46 UTC, eduardoj approved these changes

2024-08-06 12:48 UTC, saraycp approved these changes

2024-08-06 13:49 UTC, merged