Add blogpost for sprint 171 foster collaboration
openSUSE/obs-landing pull request #470
Opened 2024-08-13 12:41 UTC by rubhanazeem

2024-08-13 12:52 UTC, hellcp-work commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Custom URL's to Report bugs
```suggestion
### Custom URLs to Report bugs
```
Possessive or contraction makes no sense here

2024-08-13 13:15 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +Introducing Foster Collaboration to OBS. We're excited to introduce a suite of new features in OBS that are designed to make your workflow more efficient and intuitive.
`Foster Collaboration` is a thing for you (the name of the opportunity) but it's nothing for the people reading this blog....

2024-08-13 13:21 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +visible watcher count. These enhancements are all about giving you more control and insight. These updates are here to help you stay on top of what's most important.
I think you would have to elaborate what you mean by "control" here.

2024-08-13 13:22 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +The `Foster Collaboration` feature is part of the [beta program](/2018/10/04/the-beta-program/). Let's dive into what's new and how it can elevate your workflow.
So far are two beta features in this opportunity: 
![Screenshot from 2024-08-13 15-22-42](https://github.com/user-attachments/assets/e7bbbe82-53c9-4d74-93fc-efdc11623928)

2024-08-13 13:27 UTC, rubhanazeem commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +visible watcher count. These enhancements are all about giving you more control and insight. These updates are here to help you stay on top of what's most important.
The next sentence explains what "control" means. To stay on top of most important things.

2024-08-13 13:28 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Custom URLs to Report bugs
You should mention which feature flags this is behind (foster collaboration)

2024-08-13 13:28 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Introduction of Labels
You should mention that this is behind the labels feature flag

2024-08-13 13:31 UTC, rubhanazeem commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +The `Foster Collaboration` feature is part of the [beta program](/2018/10/04/the-beta-program/). Let's dive into what's new and how it can elevate your workflow.
Ah correct. Thanks for pointing this out

2024-08-13 13:37 UTC, rubhanazeem commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Introduction of Labels
Got it. Completely forgot there are two feature flags

2024-08-13 13:38 UTC, hennevogel commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Enhance Your Descriptions with New Markdown Support
BTW this is not deployed yet...

2024-08-14 13:28 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +title: New Features in OBS for Improved Organization and Insight
```suggestion
title: Introducing Labels and Bug Report Links
```

2024-08-14 13:39 UTC, hennevogel requested changes

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +into your work, helping you stay focused on what matters most.
```suggestion
We’ve introduced several new features in OBS designed to foster collaboration among OBS users. Customized labels for better organization, setting custom links for your bug tracker and markdown formatting for project/package descriptions. Those features are intended to give you more insight into your work, helping you stay focused on what matters most.
```

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +These labels can be applied to both packages and incoming requests, enabling you to categorize and prioritize items effectively based on their importance.
```suggestion
These labels can be applied to both packages and incoming requests, enabling you to categorize items based on their importance, topic or any other marker you can think of.
```

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +As part of the `Labels` feature flag, OBS now allows you to create and customize labels with unique names and colors, tailored to the specific needs of your projects.
```suggestion
As part of the `Labels` beta program, OBS now allows you to create and customize labels with unique names and colors, tailored to the specific needs of your projects.
```

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +This feature is part of feature flag `Foster Collaboration`. The process for reporting bugs has been significantly enhanced, offering greater flexibility for project and package maintainers.
```suggestion
This feature is part of `Foster Collaboration` beta program. The process for reporting bugs has been significantly enhanced, offering greater flexibility for project and package maintainers.
```

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +Previously, all bug reports were automatically directed to Bugzilla, which limited the ability to use other issue-tracking systems.
```suggestion
Previously, all bug reports were automatically directed to an OBS instance wide link (Bugzilla), which limited the ability to use custom issue-tracking systems.
```

2024-08-14 13:39 UTC, hennevogel commented on _posts/development/2024-08-14-introduction-labels-and-foster-collab.md
> +### Enhance Your Descriptions with New Markdown Support
I think this should go before the number of watchers as it's way more important.

2024-08-14 14:06 UTC, hennevogel approved these changes

2024-08-14 14:06 UTC, hennevogel commented
Nice one! 💐

2024-08-14 14:06 UTC, merged

2024-08-14 14:12 UTC, eduardoj commented on _posts/development/2024-08-13-introduction-foster-collab.md
> +### Enhance Your Descriptions with New Markdown Support
It is deployed since a couple of minutes now.