Create a blog post about the sprint 172
openSUSE/obs-landing pull request #472
Opened 2024-08-27 09:48 UTC by hellcp-work

2024-08-27 09:51 UTC, srbaker approved these changes

2024-08-27 10:09 UTC, hennevogel requested changes

2024-08-27 10:09 UTC, hennevogel commented on _posts/development/2024-08-27-content-moderation.md
> +In the latest set of improvements coming to OBS content moderation feature we focused on improving the experience of moderators reviewing incoming reports, to make it easier for them to comprehend th
```suggestion
In the latest set of improvements coming to OBS content moderation feature we focused on improving the experience of moderators reviewing incoming reports. By including more information about the state of reports we make it easier for moderators to comprehend the user reported content in the notifications. This will lower the time the moderators need to respond to reports.
```

2024-08-27 10:18 UTC, eduardoj commented on _includes/partials/_series-of-posts-about-content-moderation.md
> +_Our journey into [content moderation]((/2023/10/02/moderation)) began back in October 2023, initially addressing [comment locks and report categories](/2023/10/18/comment-locking-and-report-categori
```suggestion
_Our journey into [content moderation]((/2023/10/02/moderation)) began back in October 2023, initially addressing [comment locks and report categories](/2023/10/18/comment-locking-and-report-categories). Since then, we've expanded this feature to include [canned responses and moderator decisions](/2023/12/13/canned-responses-and-moderator-decisions), facilitating smoother [request reporting and the reporting of users from comments](/2023/12/21/request-reports-and-comment-reports). Following that, we've honed in on [optimizing canned responses and introducing various UI upgrades](/2024/03/06/content-moderation), Last time we focused on [improving the communication and decision making](/2024/04/30/content-moderation). This time we [improved the report notifications for moderators](/2024/08/27/content-moderation)._
```

2024-08-27 10:29 UTC, hellcp-work commented on _includes/partials/_series-of-posts-about-content-moderation.md
> +_Our journey into [content moderation]((/2023/10/02/moderation)) began back in October 2023, initially addressing [comment locks and report categories](/2023/10/18/comment-locking-and-report-categori
Applied

2024-08-27 11:12 UTC, hennevogel commented on _posts/development/2024-08-27-content-moderation.md
> +title: "Improving moderators' ability to stay informed about the reports"
```suggestion
title: "Improving notifications to stay informed about moderation reports"
```

2024-08-28 13:12 UTC, hellcp-work commented on _posts/development/2024-08-27-content-moderation.md
> +title: "Improving moderators' ability to stay informed about the reports"
Applied

2024-08-28 13:41 UTC, hennevogel commented on _posts/development/2024-08-27-content-moderation.md
> +In the latest set of improvements coming to OBS content moderation feature we focused on improving the experience of moderators reviewing incoming reports. By including more information about the sta
```suggestion
In the latest set of improvements coming to the content moderation feature we focused on improving the experience of moderators reviewing incoming reports. By including more information about the state of reports we make it easier for moderators to comprehend the user reported content in the notifications. This will lower the time the moderators need to respond to reports.
```

2024-08-28 14:10 UTC, hennevogel approved these changes

2024-08-28 14:38 UTC, eduardoj requested changes
The name of the file should not be on the past: `_posts/development/2024-08-27-content-moderation.md`.

2024-08-28 15:27 UTC, merged