Create a blog post about the sprint 174
openSUSE/obs-landing pull request #475
Opened 2024-09-23 10:49 UTC by eduardoj

2024-09-24 08:59 UTC, danidoni commented on _posts/development/2024-09-24-improving-labels.md
> +We have not only improved the way lagels are displayed, but also how they are created, assigned and managed.
```suggestion
We have not only improved the way labels are displayed, but also how they are created, assigned and managed.
```

2024-09-24 09:01 UTC, eduardoj commented on _posts/development/2024-09-24-improving-labels.md
> +We have not only improved the way lagels are displayed, but also how they are created, assigned and managed.
Fixed. Thanks!

2024-09-24 10:54 UTC, saraycp requested changes

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +First, you define the labels of a package.
```suggestion
First, you set the labels for a package.
```

Set is the verb we use in the UI.

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +First, you define the labels for a submit request.
```suggestion
First, you set the labels for a submit request.
```

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +We have streamlined the label selection process, reducing the number of clicks required when using the label selector component.
```suggestion
We have streamlined the label selection process, reducing the number of clicks required when using the label selector.
```

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +  <img src="/images/posts/2024-09-24/introduce-copying-labels.png" alt="Screenshot of the copy of labels from one project to another" />
Could you take the same screenshot but making sure the corresponding tab is visible? I mean, you do horizontal scroll on the tabs so the `Label Template` tab is visible in the screenshot. I think it'll help people to understand where to find it (in case the breadcrumb go unnoticed).

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +### Showing Labels in the List of Submit Requests
```suggestion
### Showing Labels in the List of Requests
```

Why submit requests only? We can add labels to any kind of requests, right? for example role addition request.

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +First, you define the labels for a submit request.
```suggestion
The same logic applies to requests.
First, you define the labels for a request.
```

2024-09-24 10:54 UTC, saraycp commented on _posts/development/2024-09-24-improving-labels.md
> +  <figcaption>Showing Labels in the List of Submit Requests</figcaption>
```suggestion
  <img src="/images/posts/2024-09-24/show-labels-in-list-of-requests.png" alt="Screenshot of labels in the list of requests" />
  <figcaption>Showing Labels in the List of Requests</figcaption>
```

2024-09-24 11:20 UTC, eduardoj commented on _posts/development/2024-09-24-improving-labels.md
> +  <img src="/images/posts/2024-09-24/introduce-copying-labels.png" alt="Screenshot of the copy of labels from one project to another" />
Sure. Done. Please take a look again.

I also applied all the other suggestions you made. Thanks!

2024-09-24 13:31 UTC, danidoni approved these changes

2024-09-25 10:18 UTC, saraycp approved these changes

2024-09-25 14:22 UTC, merged