Blog post for Spring 176
openSUSE/obs-landing pull request #476
Opened 2024-10-23 07:54 UTC by danidoni

2024-10-23 14:15 UTC, hennevogel requested changes

2024-10-23 14:15 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +This blog post is part of the [beta program](/2018/10/04/the-beta-program/).
A blog post is not part of the beta program...

2024-10-23 14:15 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +We've added eyecatchers on the request's diff page. The diff component now shows small highlights that help users understand what exactly changed before and after.
```suggestion
We've added eyecatchers on the request's diff page. The diff component now shows small highlights that help users understand what exactly changed.
```

2024-10-23 14:15 UTC, hennevogel commented
In general this read like a report. Like

> we did this, we did that

but this isn't what we want right? We want people to understand what is new and why it is good for them.

2024-10-23 14:38 UTC, danidoni commented
> In general this read like a report. Like
> 
> > we did this, we did that
> 
> but this isn't what we want right? We want people to understand what is new and why it is good for them.

Hm, I see, let me give it a spin

2024-10-24 09:55 UTC, eduardoj approved these changes

2024-10-24 10:21 UTC, hennevogel requested changes

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +Our recent redesign of the request page has introduced three significant improvements that make it easier for you to understand better their requests. Those improvements are part of the [beta program
```suggestion
Today we want to tell you about three significant improvements we have just introduced that make it easier to collaborate on the request page. Those improvements are part of the [beta program](/2018/10/04/the-beta-program/).
```

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +You'll notice that the review decision and the comment boxes are now combined into just one box. This will reduce the clutter on a request's conversation timeline and help you focus on _what_ you hav
Not sure I understand what you want to say with this.

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +# Less Noise on the Builds
```suggestion
## Less Noise in the Build Results
```

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +# More Clarity on the Diffs
```suggestion
## More Clarity on the Diffs
```

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +# Streamlined Conversations
```suggestion
## Less Clutter in Conversations
```

2024-10-24 10:21 UTC, hennevogel commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +The build status of a request was showing a lot of information that was not really useful for you, like the "Excluded" state. Now it shows only relevant information to the changes. This will make eas
```suggestion
The build results of a request were showing a lot of information that is not really useful to decide if you should merge the request or not, like the "Excluded" state. We limited the build results in the overview to succeeded/failed and building now. This will make easier for you to understand the state of the request and help you make a decision about it.
```

2024-10-24 10:21 UTC, hennevogel commented
> Hm, I see, let me give it a spin

You found a nice direct voice for this and worked out the benefits perfectly. Nice job!

2024-10-24 10:49 UTC, danidoni commented on _posts/development/2024-10-23-make-it-easier-for-users-to-understand-what-is-there-on-a-request.md
> +You'll notice that the review decision and the comment boxes are now combined into just one box. This will reduce the clutter on a request's conversation timeline and help you focus on _what_ you hav
Before we had two boxes right? If you wanted to write a comment, you had  to find the comment box. If you wanted to give a reason because you declined something you had to find the "decision box". Now, you only have one box, so you don't have to think where you write things anymore because there is no choice. Makes sense?

2024-10-24 10:56 UTC, danidoni commented
> You found a nice direct voice for this and worked out the benefits perfectly. Nice job!

Thanks!

2024-10-24 14:38 UTC, hennevogel approved these changes

2024-10-25 07:36 UTC, merged